import { copyFileSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { writeBrandAssets } from "../../../shared/brand-assets.mjs";
import { buildThemesData } from "../../../shared/site-theme-tokens.js";
import {
  LANGUAGE_META,
  resolveSnippetForLanguage,
} from "../../../shared/site-snippets.js";
import { loadPalettes } from "../../../src/generator/index.js";
import { loadSnippetCatalogWithMeta } from "../../../src/snippets/catalog/index.js";
import { SNIPPET_LANGUAGES } from "../../../src/snippets/registry.js";

const websiteDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const rootDir = join(websiteDir, "../..");
const generatedDir = join(websiteDir, "src", "generated");
const publicDir = join(websiteDir, "public");
const previewsSource = join(rootDir, "docs", "previews");
const iconSource = join(rootDir, "icon.png");

export async function prepareWebsiteData() {
  const palettes = await loadPalettes();
  const catalog = await loadSnippetCatalogWithMeta();
  const themes = buildThemesData(palettes);

  const paletteSummaries = palettes.map((palette) => ({
    id: palette.id,
    label: palette.label,
    preview: `/previews/${palette.id}.png`,
    accent: palette.ui.accent,
    shell: palette.ui.surfaceShell,
  }));

  const languages = SNIPPET_LANGUAGES.map(({ language }) => {
    const meta = LANGUAGE_META[language];
    const count = catalog.filter((entry) => entry.languages.includes(language)).length;
    return { ...meta, count };
  });

  const snippets = catalog.flatMap((entry) =>
    entry.languages.map((language) => {
      const resolved = resolveSnippetForLanguage(entry, language);
      const meta = LANGUAGE_META[language];
      return {
        key: entry.key,
        category: entry.category,
        language,
        languageLabel: meta.label,
        languageSlug: meta.slug,
        prefix: resolved.prefix,
        description: resolved.description,
        body: resolved.body,
        search: [
          resolved.prefix,
          resolved.description,
          entry.category,
          meta.label,
          entry.key,
        ]
          .join(" ")
          .toLowerCase(),
      };
    }),
  );

  const categories = [...new Set(catalog.map((entry) => entry.category))].sort();

  rmSync(publicDir, { recursive: true, force: true });
  mkdirSync(join(publicDir, "previews"), { recursive: true });
  const assetsDir = join(publicDir, "assets");
  mkdirSync(assetsDir, { recursive: true });

  for (const file of readdirSync(previewsSource).filter((name) => name.endsWith(".png"))) {
    copyFileSync(join(previewsSource, file), join(publicDir, "previews", file));
  }
  await writeBrandAssets(iconSource, assetsDir);

  mkdirSync(generatedDir, { recursive: true });
  const payload = {
    paletteCount: palettes.length,
    catalogCount: catalog.length,
    categoryCount: categories.length,
    palettes: paletteSummaries,
    themes,
    languages,
    snippets,
    categories,
    defaultThemeId: "ether-dusk",
  };

  writeFileSync(
    join(generatedDir, "site-data.ts"),
    `/* eslint-disable */\n/** Generated by apps/website/scripts/prepare-data.mjs — do not edit */\nexport const SITE_DATA = ${JSON.stringify(payload, null, 2)} as const;\nexport type SiteData = typeof SITE_DATA;\n`,
    "utf8",
  );

  return payload;
}

const invokedDirectly =
  process.argv[1] &&
  fileURLToPath(import.meta.url) === process.argv[1];

if (invokedDirectly) {
  const result = await prepareWebsiteData();
  console.log(
    `Prepared website data (${result.paletteCount} themes, ${result.catalogCount} snippets)`,
  );
}
