// Synced from ES7+ React/Redux/React-Native extension — npm run snippets:sync

/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "console-console-assert",
    prefix: "cas",
    description: "If the specified expression is false, the message is written to the console along with a stack trace · cas",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.assert(${1:first}, ${2:second})",
  },
  {
    key: "console-console-clear",
    prefix: "ccl",
    description: "Clears the console · ccl",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.clear()",
  },
  {
    key: "console-console-count",
    prefix: "cco",
    description: "Writes the the number of times that count() has been invoked at the same line and with the same label · cco",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.count(${1:first})",
  },
  {
    key: "console-console-dir",
    prefix: "cdi",
    description: "Prints a JavaScript representation of the specified object · cdi",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.dir(${1:first})",
  },
  {
    key: "console-console-error",
    prefix: "cer",
    description: "Displays a message in the console and also includes a stack trace from where the method was called · cer",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.error(${1:first})",
  },
  {
    key: "console-console-group",
    prefix: "cgr",
    description: "Groups and indents all following output by an additional level, until console.groupEnd() is called. · cgr",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.group('${1:first}')",
  },
  {
    key: "console-console-group-end",
    prefix: "cge",
    description: "Closes out the corresponding console.group(). · cge",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.groupEnd()",
  },
  {
    key: "console-console-info",
    prefix: "cin",
    description: "Displays a message in the console but also displays a blue information icon along with the logged message · cin",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.info(${1:first})",
  },
  {
    key: "console-console-log",
    prefix: "clg",
    description: "Displays a message in the console · clg",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.log(${1:first})",
  },
  {
    key: "console-console-log-json",
    prefix: "clj",
    description: "Logs stringified JSON property with name. · clj",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.log('${1:first}', JSON.stringify(${1:first}, null, 2))",
  },
  {
    key: "console-console-log-object",
    prefix: "clo",
    description: "Logs property with name. · clo",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.log('${1:first}', ${1:first})",
  },
  {
    key: "console-console-table",
    prefix: "ctl",
    description: "Logs table to console · ctl",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.table([${1:first}])",
  },
  {
    key: "console-console-time",
    prefix: "ctm",
    description: "Console time wrapper · ctm",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.time('${1:first}')",
  },
  {
    key: "console-console-time-end",
    prefix: "cte",
    description: "Console time end wrapper · cte",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.timeEnd('${1:first}')",
  },
  {
    key: "console-console-trace",
    prefix: "ctr",
    description: "Prints a stack trace from the point where the method was called · ctr",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.trace(${1:first})",
  },
  {
    key: "console-console-warn",
    prefix: "cwa",
    description: "Displays a message in the console but also displays a yellow warning icon along with the logged message · cwa",
    languages: ["typescript", "typescriptreact", "javascript", "javascriptreact"],
    body: "console.warn(${1:first})",
  },
];
