/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "css-flex-center",
    prefix: "flexcenter",
    description: "CSS flexbox center",
    languages: ["css"],
    body: [
      "display: flex;",
      "align-items: center;",
      "justify-content: center;",
    ],
  },
  {
    key: "css-flex-column",
    prefix: "flexcol",
    description: "CSS flex column layout",
    languages: ["css"],
    body: [
      "display: flex;",
      "flex-direction: column;",
      "gap: ${1:1rem};",
    ],
  },
  {
    key: "css-flex-row",
    prefix: "flexrow",
    description: "CSS flex row layout",
    languages: ["css"],
    body: [
      "display: flex;",
      "flex-direction: row;",
      "gap: ${1:1rem};",
    ],
  },
  {
    key: "css-grid-center",
    prefix: "gridcenter",
    description: "CSS grid center",
    languages: ["css"],
    body: [
      "display: grid;",
      "place-items: center;",
    ],
  },
  {
    key: "css-grid-layout",
    prefix: "grid",
    description: "CSS grid layout",
    languages: ["css"],
    body: [
      "display: grid;",
      "grid-template-columns: repeat(${1:3}, 1fr);",
      "gap: ${2:1rem};",
    ],
  },
  {
    key: "css-media-query",
    prefix: "media",
    description: "CSS media query",
    languages: ["css"],
    body: [
      "@media (min-width: ${1:768px}) {",
      "  $0",
      "}",
    ],
  },
  {
    key: "css-keyframes",
    prefix: "keyframes",
    description: "CSS keyframes animation",
    languages: ["css"],
    body: [
      "@keyframes ${1:animationName} {",
      "  from {",
      "    $2",
      "  }",
      "  to {",
      "    $0",
      "  }",
      "}",
    ],
  },
  {
    key: "css-animation",
    prefix: "animation",
    description: "CSS animation property",
    languages: ["css"],
    body: "animation: ${1:name} ${2:1s} ${3|ease,ease-in,ease-out,ease-in-out,linear|} ${4:0s} ${5|normal,reverse,alternate|} ${6:1} ${7|running,paused|};",
  },
  {
    key: "css-custom-properties",
    prefix: "vars",
    description: "CSS custom properties block",
    languages: ["css"],
    body: [
      ":root {",
      "  --${1:name}: ${2:value};",
      "  $0",
      "}",
    ],
  },
  {
    key: "css-custom-property-use",
    prefix: "var",
    description: "CSS custom property reference",
    languages: ["css"],
    body: "var(--${1:name}, ${2:fallback})",
  },
  {
    key: "css-box-sizing-reset",
    prefix: "boxreset",
    description: "CSS box-sizing reset",
    languages: ["css"],
    body: [
      "*,",
      "*::before,",
      "*::after {",
      "  box-sizing: border-box;",
      "}",
    ],
  },
  {
    key: "css-absolute-center",
    prefix: "abscenter",
    description: "CSS absolute center",
    languages: ["css"],
    body: [
      "position: absolute;",
      "top: 50%;",
      "left: 50%;",
      "transform: translate(-50%, -50%);",
    ],
  },
  {
    key: "css-sticky",
    prefix: "sticky",
    description: "CSS position sticky",
    languages: ["css"],
    body: [
      "position: sticky;",
      "top: ${1:0};",
      "z-index: ${2:10};",
    ],
  },
  {
    key: "css-truncate",
    prefix: "truncate",
    description: "CSS text truncate ellipsis",
    languages: ["css"],
    body: [
      "overflow: hidden;",
      "text-overflow: ellipsis;",
      "white-space: nowrap;",
    ],
  },
  {
    key: "css-line-clamp",
    prefix: "lineclamp",
    description: "CSS multi-line clamp",
    languages: ["css"],
    body: [
      "display: -webkit-box;",
      "-webkit-line-clamp: ${1:3};",
      "-webkit-box-orient: vertical;",
      "overflow: hidden;",
    ],
  },
  {
    key: "css-focus-visible",
    prefix: "focusvis",
    description: "CSS focus-visible outline",
    languages: ["css"],
    body: [
      "&:focus-visible {",
      "  outline: 2px solid ${1:currentColor};",
      "  outline-offset: 2px;",
      "}",
    ],
  },
  {
    key: "css-hover-transition",
    prefix: "hover",
    description: "CSS hover with transition",
    languages: ["css"],
    body: [
      "transition: ${1:all} ${2:200ms} ${3|ease,ease-in,ease-out,ease-in-out,linear|};",
      "",
      "&:hover {",
      "  $0",
      "}",
    ],
  },
  {
    key: "css-container-query",
    prefix: "container",
    description: "CSS container query",
    languages: ["css"],
    body: [
      "container-type: inline-size;",
      "",
      "@container (min-width: ${1:400px}) {",
      "  $0",
      "}",
    ],
  },
  {
    key: "css-aspect-ratio",
    prefix: "aspect",
    description: "CSS aspect ratio",
    languages: ["css"],
    body: "aspect-ratio: ${1:16} / ${2:9};",
  },
  {
    key: "css-visually-hidden",
    prefix: "sronly",
    description: "CSS screen reader only",
    languages: ["css"],
    body: [
      "position: absolute;",
      "width: 1px;",
      "height: 1px;",
      "padding: 0;",
      "margin: -1px;",
      "overflow: hidden;",
      "clip: rect(0, 0, 0, 0);",
      "white-space: nowrap;",
      "border: 0;",
    ],
  },
  {
    key: "css-gradient-linear",
    prefix: "gradient",
    description: "CSS linear gradient",
    languages: ["css"],
    body: "background: linear-gradient(${1:180deg}, ${2:#000}, ${3:#fff});",
  },
  {
    key: "css-shadow",
    prefix: "shadow",
    description: "CSS box shadow",
    languages: ["css"],
    body: "box-shadow: ${1:0} ${2:4px} ${3:12px} rgba(0, 0, 0, ${4:0.15});",
  },
  {
    key: "css-border-radius",
    prefix: "radius",
    description: "CSS border radius",
    languages: ["css"],
    body: "border-radius: ${1:8px};",
  },
  {
    key: "css-font-stack",
    prefix: "fontstack",
    description: "CSS system font stack",
    languages: ["css"],
    body: "font-family: system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif;",
  },
  {
    key: "css-reset-margin-padding",
    prefix: "resetmp",
    description: "CSS margin padding reset",
    languages: ["css"],
    body: [
      "margin: 0;",
      "padding: 0;",
    ],
  },
  {
    key: "css-modern-reset",
    prefix: "modernreset",
    description: "CSS modern minimal reset",
    languages: ["css"],
    body: [
      "*,",
      "*::before,",
      "*::after {",
      "  box-sizing: border-box;",
      "}",
      "",
      "html:focus-within {",
      "  scroll-behavior: smooth;",
      "}",
      "",
      "body {",
      "  min-height: 100vh;",
      "  line-height: 1.5;",
      "  text-rendering: optimizeLegibility;",
      "  -webkit-font-smoothing: antialiased;",
      "}",
      "",
      "img, picture, video, canvas, svg {",
      "  display: block;",
      "  max-width: 100%;",
      "}",
    ],
  },
  {
    key: "css-clamp-fluid-type",
    prefix: "fluidtype",
    description: "CSS fluid typography with clamp",
    languages: ["css"],
    body: "font-size: clamp(${1:1rem}, ${2:0.5rem} + ${3:2vw}, ${4:2rem});",
  },
  {
    key: "css-prefers-reduced-motion",
    prefix: "reducedmotion",
    description: "CSS prefers-reduced-motion guard",
    languages: ["css"],
    body: [
      "@media (prefers-reduced-motion: reduce) {",
      "  *,",
      "  *::before,",
      "  *::after {",
      "    animation-duration: 0.01ms !important;",
      "    animation-iteration-count: 1 !important;",
      "    transition-duration: 0.01ms !important;",
      "    scroll-behavior: auto !important;",
      "  }",
      "}",
    ],
  },
  {
    key: "css-dark-mode",
    prefix: "darkmode",
    description: "CSS prefers-color-scheme dark mode",
    languages: ["css"],
    body: [
      "@media (prefers-color-scheme: dark) {",
      "  :root {",
      "    color-scheme: dark;",
      "    $0",
      "  }",
      "}",
    ],
  },
  {
    key: "css-backdrop-blur",
    prefix: "backdrop",
    description: "CSS backdrop blur glass effect",
    languages: ["css"],
    body: [
      "background: rgba(255, 255, 255, ${1:0.72});",
      "backdrop-filter: blur(${2:12px});",
      "-webkit-backdrop-filter: blur(${2:12px});",
    ],
  },
  {
    key: "css-scroll-snap",
    prefix: "scrollsnap",
    description: "CSS scroll snap container",
    languages: ["css"],
    body: [
      "display: flex;",
      "overflow-x: auto;",
      "scroll-snap-type: x mandatory;",
      "gap: ${1:1rem};",
      "",
      "& > * {",
      "  scroll-snap-align: start;",
      "  flex: 0 0 ${2:80%};",
      "}",
    ],
  },
  {
    key: "css-layer",
    prefix: "layer",
    description: "CSS cascade layer",
    languages: ["css"],
    body: [
      "@layer ${1:base}, ${2:components}, ${3:utilities};",
      "",
      "@layer ${1:base} {",
      "  $0",
      "}",
    ],
  },
  {
    key: "css-is-where",
    prefix: "iswhere",
    description: "CSS :is() selector group",
    languages: ["css"],
    body: ":is(${1:h1}, ${2:h2}, ${3:h3}) {",
  },
  {
    key: "css-logical-sizing",
    prefix: "logical",
    description: "CSS logical properties",
    languages: ["css"],
    body: [
      "inline-size: ${1:100%};",
      "block-size: ${2:auto};",
      "padding-inline: ${3:1rem};",
      "padding-block: ${4:0.5rem};",
    ],
  },
  {
    key: "css-subgrid",
    prefix: "subgrid",
    description: "CSS subgrid layout",
    languages: ["css"],
    body: [
      "display: grid;",
      "grid-template-columns: subgrid;",
      "grid-column: span ${1:3};",
    ],
  },
  {
    key: "css-inset-shadow",
    prefix: "insetshadow",
    description: "CSS inset box shadow",
    languages: ["css"],
    body: "box-shadow: inset 0 1px 2px rgba(0, 0, 0, ${1:0.08});",
  },
  {
    key: "css-fit-content",
    prefix: "fitcontent",
    description: "CSS fit-content sizing",
    languages: ["css"],
    body: "width: fit-content; max-width: 100%;",
  },
];
