// Synced from ES7+ React/Redux/React-Native extension (vendored in-repo)

/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "hooks-use-callback",
    prefix: "useCallbackSnippet",
    description: "Use Callback · useCallbackSnippet",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "useCallback(",
      "  () => {",
      "    ${1:first}",
      "  },",
      "  [${2:second}],",
      ")",
      "",
    ],
  },
  {
    key: "hooks-use-context",
    prefix: "useContextSnippet",
    description: "Use Context · useContextSnippet",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "const ${1:first} = useContext(${2:second})",
  },
  {
    key: "hooks-use-effect",
    prefix: "useEffectSnippet",
    description: "Use Effect · useEffectSnippet",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "useEffect(() => {",
      "  ${1:first}",
      "",
      "  return () => {",
      "    ${2:second}",
      "  }",
      "}, [${3:third}])",
      "",
    ],
  },
  {
    key: "hooks-use-imperative-handle",
    prefix: "useImperativeHandleSnippet",
    description: "Use Imperative Handle · useImperativeHandleSnippet",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "useImperativeHandle(",
      "  ${1:first},",
      "  () => {",
      "    ${2:second}",
      "  },",
      "  [${3:third}],",
      ")",
    ],
  },
  {
    key: "hooks-use-layout-effect",
    prefix: "useLayoutEffectSnippet",
    description: "Use Layout Effect · useLayoutEffectSnippet",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "useLayoutEffect(() => {",
      "  ${1:first}",
      "",
      "  return () => {",
      "    ${2:second}",
      "  };",
      "}, [${3:third}])",
    ],
  },
  {
    key: "hooks-use-memo",
    prefix: "useMemoSnippet",
    description: "Use Memo · useMemoSnippet",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "useMemo(() => ${1:first}, [${2:second}])",
  },
  {
    key: "hooks-use-reducer",
    prefix: "useReducerSnippet",
    description: "Use Reducer · useReducerSnippet",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "const [state, dispatch] = useReducer(${1:first}, ${2:second}, ${3:third})",
  },
  {
    key: "hooks-use-ref",
    prefix: "useRefSnippet",
    description: "Use Ref · useRefSnippet",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "const ${1:first} = useRef(${2:second})",
  },
  {
    key: "hooks-use-state",
    prefix: "useStateSnippet",
    description: "Use State · useStateSnippet",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "const [${1:first}, set${1/(.*)/${1:/capitalize}/}] = useState(${2:second})",
  },
];
