/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "html5-boilerplate",
    prefix: "html5",
    description: "HTML5 document boilerplate",
    languages: ["html"],
    body: [
      "<!DOCTYPE html>",
      "<html lang=\"${1:en}\">",
      "<head>",
      "  <meta charset=\"UTF-8\">",
      "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">",
      "  <meta name=\"description\" content=\"${2:Page description}\">",
      "  <meta name=\"theme-color\" content=\"${3:#ffffff}\">",
      "  <title>${4:Document}</title>",
      "  <link rel=\"icon\" href=\"${5:/favicon.ico}\" sizes=\"any\">",
      "  <link rel=\"stylesheet\" href=\"${6:/styles.css}\">",
      "  $0",
      "</head>",
      "<body>",
      "  <a class=\"skip-link\" href=\"#main-content\">Skip to content</a>",
      "  <main id=\"main-content\">",
      "",
      "  </main>",
      "  <script type=\"module\" src=\"${7:/main.js}\"></script>",
      "</body>",
      "</html>",
    ],
  },
  {
    key: "html-meta-viewport",
    prefix: "viewport",
    description: "HTML viewport meta tag",
    languages: ["html"],
    body: "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">",
  },
  {
    key: "html-meta-description",
    prefix: "metadesc",
    description: "HTML meta description",
    languages: ["html"],
    body: "<meta name=\"description\" content=\"${1:description}\">",
  },
  {
    key: "html-link-stylesheet",
    prefix: "linkcss",
    description: "HTML link stylesheet",
    languages: ["html"],
    body: "<link rel=\"stylesheet\" href=\"${1:styles.css}\">",
  },
  {
    key: "html-script-defer",
    prefix: "scriptdef",
    description: "HTML script with defer",
    languages: ["html"],
    body: "<script src=\"${1:app.js}\" defer></script>",
  },
  {
    key: "html-script-module",
    prefix: "scriptmod",
    description: "HTML ES module script",
    languages: ["html"],
    body: "<script type=\"module\" src=\"${1:app.js}\"></script>",
  },
  {
    key: "html-semantic-header",
    prefix: "header",
    description: "HTML header element",
    languages: ["html"],
    body: [
      "<header>",
      "  $0",
      "</header>",
    ],
  },
  {
    key: "html-semantic-nav",
    prefix: "nav",
    description: "HTML nav element",
    languages: ["html"],
    body: [
      "<nav aria-label=\"${1:Main}\">",
      "  $0",
      "</nav>",
    ],
  },
  {
    key: "html-semantic-main",
    prefix: "main",
    description: "HTML main element",
    languages: ["html"],
    body: [
      "<main>",
      "  $0",
      "</main>",
    ],
  },
  {
    key: "html-semantic-section",
    prefix: "section",
    description: "HTML section element",
    languages: ["html"],
    body: [
      "<section aria-labelledby=\"${1:section-heading}\">",
      "  $0",
      "</section>",
    ],
  },
  {
    key: "html-semantic-article",
    prefix: "article",
    description: "HTML article element",
    languages: ["html"],
    body: [
      "<article>",
      "  $0",
      "</article>",
    ],
  },
  {
    key: "html-semantic-footer",
    prefix: "footer",
    description: "HTML footer element",
    languages: ["html"],
    body: [
      "<footer>",
      "  $0",
      "</footer>",
    ],
  },
  {
    key: "html-form",
    prefix: "form",
    description: "HTML form",
    languages: ["html"],
    body: [
      "<form action=\"${1:/submit}\" method=\"${2|post,get|}\">",
      "  $0",
      "</form>",
    ],
  },
  {
    key: "html-input-text",
    prefix: "input",
    description: "HTML text input with label",
    languages: ["html"],
    body: [
      "<label for=\"${1:id}\">${2:Label}</label>",
      "<input id=\"${1:id}\" name=\"${3:name}\" type=\"${4|text,email,password,number,tel,url,search|}\" ${5:required}>",
    ],
  },
  {
    key: "html-textarea",
    prefix: "textarea",
    description: "HTML textarea with label",
    languages: ["html"],
    body: [
      "<label for=\"${1:id}\">${2:Label}</label>",
      "<textarea id=\"${1:id}\" name=\"${3:name}\" rows=\"${4:4}\"></textarea>",
    ],
  },
  {
    key: "html-select",
    prefix: "select",
    description: "HTML select with label",
    languages: ["html"],
    body: [
      "<label for=\"${1:id}\">${2:Label}</label>",
      "<select id=\"${1:id}\" name=\"${3:name}\">",
      "  <option value=\"${4:value}\">${5:Option}</option>",
      "  $0",
      "</select>",
    ],
  },
  {
    key: "html-button",
    prefix: "button",
    description: "HTML button",
    languages: ["html"],
    body: "<button type=\"${1|button,submit,reset|}\">${2:Button}</button>",
  },
  {
    key: "html-aria-label",
    prefix: "aria",
    description: "HTML aria-label attribute",
    languages: ["html"],
    body: "aria-label=\"${1:description}\"",
  },
  {
    key: "html-skip-link",
    prefix: "skiplink",
    description: "HTML skip to content link",
    languages: ["html"],
    body: "<a class=\"skip-link\" href=\"#${1:main-content}\">Skip to content</a>",
  },
  {
    key: "html-img-responsive",
    prefix: "img",
    description: "HTML responsive image",
    languages: ["html"],
    body: "<img src=\"${1:image.jpg}\" alt=\"${2:description}\" width=\"${3:800}\" height=\"${4:600}\" loading=\"lazy\">",
  },
  {
    key: "html-picture",
    prefix: "picture",
    description: "HTML picture element",
    languages: ["html"],
    body: [
      "<picture>",
      "  <source srcset=\"${1:image.webp}\" type=\"image/webp\">",
      "  <img src=\"${2:image.jpg}\" alt=\"${3:description}\">",
      "</picture>",
    ],
  },
  {
    key: "html-video",
    prefix: "video",
    description: "HTML video element",
    languages: ["html"],
    body: [
      "<video controls width=\"${1:640}\" height=\"${2:360}\">",
      "  <source src=\"${3:video.mp4}\" type=\"video/mp4\">",
      "  Your browser does not support the video tag.",
      "</video>",
    ],
  },
  {
    key: "html-details-summary",
    prefix: "details",
    description: "HTML details and summary",
    languages: ["html"],
    body: [
      "<details>",
      "  <summary>${1:Summary}</summary>",
      "  $0",
      "</details>",
    ],
  },
  {
    key: "html-unordered-list",
    prefix: "ul",
    description: "HTML unordered list",
    languages: ["html"],
    body: [
      "<ul>",
      "  <li>$0</li>",
      "</ul>",
    ],
  },
  {
    key: "html-ordered-list",
    prefix: "ol",
    description: "HTML ordered list",
    languages: ["html"],
    body: [
      "<ol>",
      "  <li>$0</li>",
      "</ol>",
    ],
  },
  {
    key: "html-anchor",
    prefix: "a",
    description: "HTML anchor link",
    languages: ["html"],
    body: "<a href=\"${1:url}\">${2:Link text}</a>",
  },
  {
    key: "html-open-graph",
    prefix: "og",
    description: "HTML Open Graph meta tags",
    languages: ["html"],
    body: [
      "<meta property=\"og:title\" content=\"${1:Title}\">",
      "<meta property=\"og:description\" content=\"${2:Description}\">",
      "<meta property=\"og:type\" content=\"${3|website,article|}\">",
      "<meta property=\"og:url\" content=\"${4:https://example.com}\">",
      "<meta property=\"og:image\" content=\"${5:https://example.com/og-image.jpg}\">",
    ],
  },
  {
    key: "html-canonical",
    prefix: "canonical",
    description: "HTML canonical link",
    languages: ["html"],
    body: "<link rel=\"canonical\" href=\"${1:https://example.com/page}\">",
  },
  {
    key: "html-preload",
    prefix: "preload",
    description: "HTML preload resource hint",
    languages: ["html"],
    body: "<link rel=\"preload\" href=\"${1:/font.woff2}\" as=\"${2|font,style,script,fetch|}\" crossorigin>",
  },
  {
    key: "html-dialog",
    prefix: "dialog",
    description: "HTML dialog element",
    languages: ["html"],
    body: [
      "<dialog id=\"${1:dialog-id}\" aria-labelledby=\"${2:dialog-title}\">",
      "  <h2 id=\"${2:dialog-title}\">${3:Dialog title}</h2>",
      "  $0",
      "  <form method=\"dialog\">",
      "    <button value=\"cancel\">Close</button>",
      "  </form>",
      "</dialog>",
    ],
  },
  {
    key: "html-fieldset",
    prefix: "fieldset",
    description: "HTML fieldset with legend",
    languages: ["html"],
    body: [
      "<fieldset>",
      "  <legend>${1:Group label}</legend>",
      "  $0",
      "</fieldset>",
    ],
  },
  {
    key: "html-table-accessible",
    prefix: "table",
    description: "HTML accessible data table",
    languages: ["html"],
    body: [
      "<table>",
      "  <caption>${1:Table description}</caption>",
      "  <thead>",
      "    <tr>",
      "      <th scope=\"col\">${2:Column}</th>",
      "    </tr>",
      "  </thead>",
      "  <tbody>",
      "    <tr>",
      "      <td>$0</td>",
      "    </tr>",
      "  </tbody>",
      "</table>",
    ],
  },
  {
    key: "html-iframe-sandbox",
    prefix: "iframe",
    description: "HTML sandboxed iframe",
    languages: ["html"],
    body: "<iframe src=\"${1:url}\" title=\"${2:Embedded content}\" sandbox=\"${3|allow-scripts,allow-same-origin|}\" loading=\"lazy\"></iframe>",
  },
  {
    key: "html-checkbox",
    prefix: "checkbox",
    description: "HTML checkbox with label",
    languages: ["html"],
    body: [
      "<label>",
      "  <input type=\"checkbox\" name=\"${1:name}\" value=\"${2:value}\" ${3:checked}>",
      "  ${4:Label text}",
      "</label>",
    ],
  },
  {
    key: "html-radio-group",
    prefix: "radio",
    description: "HTML radio button group",
    languages: ["html"],
    body: [
      "<fieldset>",
      "  <legend>${1:Choose an option}</legend>",
      "  <label>",
      "    <input type=\"radio\" name=\"${2:group}\" value=\"${3:option-a}\" checked>",
      "    ${4:Option A}",
      "  </label>",
      "  <label>",
      "    <input type=\"radio\" name=\"${2:group}\" value=\"${5:option-b}\">",
      "    ${6:Option B}",
      "  </label>",
      "  $0",
      "</fieldset>",
    ],
  },
  {
    key: "html-datalist",
    prefix: "datalist",
    description: "HTML datalist autocomplete",
    languages: ["html"],
    body: [
      "<label for=\"${1:input-id}\">${2:Label}</label>",
      "<input id=\"${1:input-id}\" name=\"${3:name}\" list=\"${4:list-id}\">",
      "<datalist id=\"${4:list-id}\">",
      "  <option value=\"${5:Option}\"></option>",
      "  $0",
      "</datalist>",
    ],
  },
  {
    key: "html-landmark-layout",
    prefix: "layout",
    description: "HTML semantic page layout",
    languages: ["html"],
    body: [
      "<header>",
      "  <nav aria-label=\"Primary\">$1</nav>",
      "</header>",
      "<main id=\"main-content\">",
      "  $0",
      "</main>",
      "<footer>",
      "  $2",
      "</footer>",
    ],
  },
];
