// Synced from ES7+ React/Redux/React-Native extension — npm run snippets:sync

/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "imports-import",
    prefix: "imp",
    description: "Import · imp",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import ${2:second} from '${1:first}'",
  },
  {
    key: "imports-import-as",
    prefix: "ima",
    description: "Import As · ima",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import { ${2:second} as ${3:third} } from '${1:first}'",
  },
  {
    key: "imports-import-browser-router",
    prefix: "imbr",
    description: "Import Browser Router · imbr",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import { BrowserRouter as Router } from 'react-router-dom'",
  },
  {
    key: "imports-import-browser-router-with-route-and-nav-link",
    prefix: "imrr",
    description: "Import Browser Router With Route And Nav Link · imrr",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "import { BrowserRouter as Router, Route, NavLink } from 'react-router-dom'",
      "",
    ],
  },
  {
    key: "imports-import-destructing",
    prefix: "imd",
    description: "Import Destructing · imd",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import { ${2:second} } from '${1:first}'",
  },
  {
    key: "imports-import-everything",
    prefix: "ime",
    description: "Import Everything · ime",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import * as ${2:second} from '${1:first}'",
  },
  {
    key: "imports-import-no-module-name",
    prefix: "imn",
    description: "Import No Module Name · imn",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import '${1:first}'",
  },
  {
    key: "imports-import-prop-types",
    prefix: "impt",
    description: "Import Prop Types · impt",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import PropTypes from 'prop-types'",
  },
  {
    key: "imports-import-react",
    prefix: "imr",
    description: "Import React · imr",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import React from 'react'",
  },
  {
    key: "imports-import-react-dom",
    prefix: "imrd",
    description: "Import React Dom · imrd",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import ReactDOM from 'react-dom'",
  },
  {
    key: "imports-import-react-with-component",
    prefix: "imrc",
    description: "Import React With Component · imrc",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import React, { Component } from 'react'",
  },
  {
    key: "imports-import-react-with-component-and-prop-types",
    prefix: "imrcp",
    description: "Import React With Component And Prop Types · imrcp",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "import React, { Component } from 'react'",
      "import PropTypes from 'prop-types'",
      "",
    ],
  },
  {
    key: "imports-import-react-with-memo",
    prefix: "imrm",
    description: "Import React With Memo · imrm",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import React, { memo } from 'react'",
  },
  {
    key: "imports-import-react-with-memo-and-prop-types",
    prefix: "imrmp",
    description: "Import React With Memo And Prop Types · imrmp",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "import React, { memo } from 'react'",
      "import PropTypes from 'prop-types'",
      "",
    ],
  },
  {
    key: "imports-import-react-with-pure-component",
    prefix: "imrpc",
    description: "Import React With Pure Component · imrpc",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import React, { PureComponent } from 'react'",
  },
  {
    key: "imports-import-react-with-pure-component-and-prop-types",
    prefix: "imrpcp",
    description: "Import React With Pure Component And Prop Types · imrpcp",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "import React, { PureComponent } from 'react'",
      "import PropTypes from 'prop-types'",
      "",
    ],
  },
  {
    key: "imports-import-router-link",
    prefix: "imbrl",
    description: "Import Router Link · imbrl",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import { Link } from 'react-router-dom'",
  },
  {
    key: "imports-import-router-nav-link",
    prefix: "imbrnl",
    description: "Import Router Nav Link · imbrnl",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import { NavLink } from 'react-router-dom'",
  },
  {
    key: "imports-import-router-setup",
    prefix: "imbrc",
    description: "Import Router Setup · imbrc",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import { Route, Switch, NavLink, Link } from 'react-router-dom'",
  },
  {
    key: "imports-import-router-switch",
    prefix: "imbrs",
    description: "Import Router Switch · imbrs",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import { Switch } from 'react-router-dom'",
  },
];
