/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "js-function",
    prefix: "fn",
    description: "JavaScript function declaration",
    languages: ["javascript"],
    body: ["function ${1:name}(${2:params}) {", "  $0", "}"],
  },
  {
    key: "js-async-function",
    prefix: "afn",
    description: "JavaScript async function",
    languages: ["javascript"],
    body: ["async function ${1:name}(${2:params}) {", "  $0", "}"],
  },
  {
    key: "js-arrow-function",
    prefix: "arrow",
    description: "JavaScript arrow function",
    languages: ["javascript"],
    body: ["const ${1:name} = (${2:params}) => {", "  $0", "};"],
  },
  {
    key: "js-arrow-function-expression",
    prefix: "arrowfn",
    description: "JavaScript arrow function one-liner",
    languages: ["javascript"],
    body: "const ${1:name} = (${2:params}) => $0;",
  },
  {
    key: "js-iife",
    prefix: "iife",
    description: "JavaScript immediately invoked function",
    languages: ["javascript"],
    body: ["(function (${1:params}) {", "  $0", "})(${2:args});"],
  },
  {
    key: "js-import",
    prefix: "im",
    description: "JavaScript import statement",
    languages: ["javascript"],
    body: 'import ${1:module} from "${2:module}";',
  },
  {
    key: "js-import-dynamic",
    prefix: "imdyn",
    description: "JavaScript dynamic import",
    languages: ["javascript"],
    body: 'const ${1:module} = await import("${2:module}");',
  },
  {
    key: "js-export-named",
    prefix: "ex",
    description: "JavaScript named export",
    languages: ["javascript"],
    body: "export { ${1:name} };",
  },
  {
    key: "js-export-all",
    prefix: "exall",
    description: "JavaScript export all",
    languages: ["javascript"],
    body: 'export * from "${1:module}";',
  },
  {
    key: "js-try-catch",
    prefix: "try",
    description: "JavaScript try catch",
    languages: ["javascript"],
    body: ["try {", "  $1", "} catch (${2:error}) {", "  $0", "}"],
  },
  {
    key: "js-try-catch-finally",
    prefix: "tryf",
    description: "JavaScript try catch finally",
    languages: ["javascript"],
    body: [
      "try {",
      "  $1",
      "} catch (${2:error}) {",
      "  $3",
      "} finally {",
      "  $0",
      "}",
    ],
  },
  {
    key: "js-for-of",
    prefix: "forof",
    description: "JavaScript for...of loop",
    languages: ["javascript"],
    body: ["for (const ${1:item} of ${2:iterable}) {", "  $0", "}"],
  },
  {
    key: "js-for-in",
    prefix: "forin",
    description: "JavaScript for...in loop",
    languages: ["javascript"],
    body: ["for (const ${1:key} in ${2:object}) {", "  $0", "}"],
  },
  {
    key: "js-switch",
    prefix: "switch",
    description: "JavaScript switch statement",
    languages: ["javascript"],
    body: [
      "switch (${1:value}) {",
      "  case ${2:case}:",
      "    $0",
      "    break;",
      "  default:",
      "    break;",
      "}",
    ],
  },
  {
    key: "js-if",
    prefix: "if",
    description: "JavaScript if statement",
    languages: ["javascript"],
    body: ["if (${1:condition}) {", "  $0", "}"],
  },
  {
    key: "js-if-else",
    prefix: "ife",
    description: "JavaScript if else statement",
    languages: ["javascript"],
    body: ["if (${1:condition}) {", "  $2", "} else {", "  $0", "}"],
  },
  {
    key: "js-console-log",
    prefix: "cl",
    description: "JavaScript console.log",
    languages: ["javascript"],
    body: "console.log(${1:value});",
  },
  {
    key: "js-console-error",
    prefix: "ce",
    description: "JavaScript console.error",
    languages: ["javascript"],
    body: "console.error(${1:value});",
  },
  {
    key: "js-class",
    prefix: "class",
    description: "JavaScript class",
    languages: ["javascript"],
    body: [
      "class ${1:Name} {",
      "  constructor(${2:params}) {",
      "    $0",
      "  }",
      "}",
    ],
  },
  {
    key: "js-destructure-object",
    prefix: "dest",
    description: "JavaScript object destructuring",
    languages: ["javascript"],
    body: "const { ${1:property} } = ${2:object};",
  },
  {
    key: "js-destructure-array",
    prefix: "desta",
    description: "JavaScript array destructuring",
    languages: ["javascript"],
    body: "const [${1:first}, ${2:second}] = ${3:array};",
  },
  {
    key: "js-optional-chaining",
    prefix: "optchain",
    description: "JavaScript optional chaining",
    languages: ["javascript"],
    body: "${1:object}?.${2:property}",
  },
  {
    key: "js-nullish-coalescing",
    prefix: "nullish",
    description: "JavaScript nullish coalescing",
    languages: ["javascript"],
    body: "${1:value} ?? ${2:fallback}",
  },
  {
    key: "js-fetch",
    prefix: "fetch",
    description: "JavaScript fetch with error handling",
    languages: ["javascript"],
    body: [
      'const response = await fetch("${1:/api/data}", {',
      '  method: "${2|GET,POST,PUT,PATCH,DELETE|}",',
      "  headers: {",
      '    "Content-Type": "application/json",',
      '    Accept: "application/json",',
      "  },",
      "  ${3:body: JSON.stringify(payload),}",
      "});",
      "",
      "if (!response.ok) {",
      "  throw new Error(`Request failed: ${response.status}`);",
      "}",
      "",
      "const ${4:data} = await response.json();",
      "$0",
    ],
  },
  {
    key: "js-fetch-abort",
    prefix: "fetchabort",
    description: "JavaScript fetch with AbortController",
    languages: ["javascript"],
    body: [
      "const controller = new AbortController();",
      "",
      "try {",
      '  const response = await fetch("${1:/api/data}", {',
      "    signal: controller.signal,",
      "  });",
      "",
      "  if (!response.ok) {",
      "    throw new Error(`Request failed: ${response.status}`);",
      "  }",
      "",
      "  const ${2:data} = await response.json();",
      "  $0",
      "} finally {",
      "  controller.abort();",
      "}",
    ],
  },
  {
    key: "js-debounce",
    prefix: "debounce",
    description: "JavaScript debounce function",
    languages: ["javascript"],
    body: [
      "function debounce(${1:fn}, ${2:delayMs} = 300) {",
      "  let timer;",
      "",
      "  return function debounced(...args) {",
      "    clearTimeout(timer);",
      "    timer = setTimeout(() => ${1:fn}(...args), ${2:delayMs});",
      "  };",
      "}",
    ],
  },
  {
    key: "js-throttle",
    prefix: "throttle",
    description: "JavaScript throttle function",
    languages: ["javascript"],
    body: [
      "function throttle(${1:fn}, ${2:limitMs} = 300) {",
      "  let inThrottle = false;",
      "",
      "  return function throttled(...args) {",
      "    if (inThrottle) return;",
      "    inThrottle = true;",
      "    ${1:fn}(...args);",
      "    setTimeout(() => { inThrottle = false; }, ${2:limitMs});",
      "  };",
      "}",
    ],
  },
  {
    key: "js-array-map-filter",
    prefix: "pipe",
    description: "JavaScript map filter reduce pipeline",
    languages: ["javascript"],
    body: [
      "const ${1:result} = ${2:items}",
      "  .filter((${3:item}) => ${4:condition})",
      "  .map((${3:item}) => ${5:transform})",
      "  .reduce((${6:acc}, ${3:item}) => ${7:accumulator}, ${8:initial});",
    ],
  },
  {
    key: "js-object-entries",
    prefix: "entries",
    description: "JavaScript Object.entries iteration",
    languages: ["javascript"],
    body: [
      "for (const [${1:key}, ${2:value}] of Object.entries(${3:object})) {",
      "  $0",
      "}",
    ],
  },
  {
    key: "js-array-find",
    prefix: "find",
    description: "JavaScript array find",
    languages: ["javascript"],
    body: "const ${1:found} = ${2:items}.find((${3:item}) => ${4:condition});",
  },
  {
    key: "js-array-some-every",
    prefix: "some",
    description: "JavaScript array some check",
    languages: ["javascript"],
    body: "const ${1:hasMatch} = ${2:items}.some((${3:item}) => ${4:condition});",
  },
  {
    key: "js-set-map",
    prefix: "setmap",
    description: "JavaScript Set from array",
    languages: ["javascript"],
    body: "const ${1:unique} = [...new Set(${2:items})];",
  },
  {
    key: "js-group-by",
    prefix: "groupby",
    description: "JavaScript groupBy with reduce",
    languages: ["javascript"],
    body: [
      "const ${1:grouped} = ${2:items}.reduce((acc, ${3:item}) => {",
      "  const key = ${4:item.category};",
      "  (acc[key] ??= []).push(${3:item});",
      "  return acc;",
      "}, {});",
    ],
  },
  {
    key: "js-jsdoc-function",
    prefix: "jsdoc",
    description: "JavaScript JSDoc function",
    languages: ["javascript"],
    body: [
      "/**",
      " * ${1:Description}",
      " * @param {${2:type}} ${3:param}",
      " * @returns {${4:ReturnType}}",
      " */",
    ],
  },
  {
    key: "js-event-listener",
    prefix: "addevent",
    description: "JavaScript addEventListener with cleanup",
    languages: ["javascript"],
    body: [
      "const controller = new AbortController();",
      "",
      '${1:element}.addEventListener("${2:click}", (${3:event}) => {',
      "  $0",
      "}, { signal: controller.signal });",
      "",
      "// controller.abort() to remove listener",
    ],
  },
  {
    key: "js-module-export",
    prefix: "mod",
    description: "JavaScript ES module export block",
    languages: ["javascript"],
    body: ["export function ${1:name}(${2:params}) {", "  $0", "}"],
  },
  {
    key: "js-while",
    prefix: "while",
    description: "JavaScript while loop",
    languages: ["javascript"],
    body: ["while (${1:condition}) {", "  $0", "}"],
  },
  {
    key: "js-do-while",
    prefix: "dowhile",
    description: "JavaScript do while loop",
    languages: ["javascript"],
    body: ["do {", "  $0", "} while (${1:condition});"],
  },
  {
    key: "js-ternary",
    prefix: "ternary",
    description: "JavaScript ternary expression",
    languages: ["javascript"],
    body: "${1:condition} ? ${2:trueValue} : ${3:falseValue}",
  },
  {
    key: "js-template-literal",
    prefix: "tpl",
    description: "JavaScript template literal",
    languages: ["javascript"],
    body: "`${1:text} ${${2:variable}}`",
  },
  {
    key: "js-promise-all-settled",
    prefix: "allsettled",
    description: "JavaScript Promise.allSettled parallel tasks",
    languages: ["javascript"],
    body: [
      "const results = await Promise.allSettled([",
      "  ${1:taskA()},",
      "  ${2:taskB()},",
      "]);",
      "",
      "const fulfilled = results",
      '  .filter((result) => result.status === "fulfilled")',
      "  .map((result) => result.value);",
      "$0",
    ],
  },
  {
    key: "js-structured-clone",
    prefix: "clone",
    description: "JavaScript structuredClone deep copy",
    languages: ["javascript"],
    body: "const ${1:copy} = structuredClone(${2:original});",
  },
  {
    key: "js-array-to-sorted",
    prefix: "tosorted",
    description: "JavaScript immutable Array.toSorted",
    languages: ["javascript"],
    body: "const ${1:sorted} = ${2:items}.toSorted((a, b) => a.localeCompare(b));",
  },
  {
    key: "js-iterator-filter",
    prefix: "iterfilter",
    description: "JavaScript Iterator.from filter map",
    languages: ["javascript"],
    body: [
      "const ${1:result} = Iterator.from(${2:items})",
      "  .filter((${3:item}) => ${4:condition})",
      "  .map((${3:item}) => ${5:transform})",
      "  .toArray();",
    ],
  },
  {
    key: "js-url-search-params",
    prefix: "urlparams",
    description: "JavaScript URLSearchParams builder",
    languages: ["javascript"],
    body: [
      "const params = new URLSearchParams({",
      "  ${1:key}: ${2:value},",
      "  $0",
      "});",
      "const query = params.toString();",
    ],
  },
  {
    key: "js-weakmap-cache",
    prefix: "weakcache",
    description: "JavaScript WeakMap memoization cache",
    languages: ["javascript"],
    body: [
      "const cache = new WeakMap();",
      "",
      "function ${1:memoize}(key, compute) {",
      "  if (cache.has(key)) return cache.get(key);",
      "  const value = compute();",
      "  cache.set(key, value);",
      "  return value;",
      "}",
    ],
  },
  {
    key: "js-read-env",
    prefix: "env",
    description: "JavaScript process.env with fallback",
    languages: ["javascript"],
    body: "const ${1:PORT} = Number(process.env.${1:PORT} ?? ${2:3000});",
  },
  {
    key: "js-event-emitter",
    prefix: "emitter",
    description: "JavaScript EventTarget pub/sub pattern",
    languages: ["javascript"],
    body: [
      "const bus = new EventTarget();",
      "",
      "function on${1:Event}(handler) {",
      '  bus.addEventListener("${1:event}", handler);',
      '  return () => bus.removeEventListener("${1:event}", handler);',
      "}",
      "",
      "function emit${1:Event}(detail) {",
      '  bus.dispatchEvent(new CustomEvent("${1:event}", { detail }));',
      "}",
    ],
  },
];
