/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "node-fetch-handler",
    prefix: "nodefetch",
    description: "Node.js native fetch API call with error handling",
    languages: ["typescript", "javascript"],
    body: [
      'const response = await fetch("${1:https://api.example.com/resource}", {',
      '  method: "${2|GET,POST,PUT,PATCH,DELETE|}",',
      "  headers: {",
      '    Accept: "application/json",',
      '    "Content-Type": "application/json",',
      "  },",
      "  ${3:body: JSON.stringify(payload),}",
      "});",
      "",
      "if (!response.ok) {",
      "  throw new Error(`Upstream request failed: ${response.status}`);",
      "}",
      "",
      "const ${4:data} = await response.json();",
      "$0",
    ],
    variants: {
      typescript: {
        body: [
          'const response = await fetch("${1:https://api.example.com/resource}", {',
          '  method: "${2|GET,POST,PUT,PATCH,DELETE|}",',
          "  headers: {",
          '    Accept: "application/json",',
          '    "Content-Type": "application/json",',
          "  },",
          "  ${3:body: JSON.stringify(payload),}",
          "});",
          "",
          "if (!response.ok) {",
          "  throw new Error(`Upstream request failed: ${response.status}`);",
          "}",
          "",
          "const ${4:data}: ${5:ResponseType} = await response.json();",
          "$0",
        ],
      },
    },
  },
  {
    key: "node-http-server",
    prefix: "nodehttp",
    description: "Node.js http.createServer handler",
    languages: ["typescript", "javascript"],
    body: [
      'import http from "node:http";',
      "",
      "const server = http.createServer(async (req, res) => {",
      "  try {",
      '    if (req.method === "GET" && req.url === "${1:/health}") {',
      '      res.writeHead(200, { "Content-Type": "application/json" });',
      "      res.end(JSON.stringify({ ok: true }));",
      "      return;",
      "    }",
      "",
      '    res.writeHead(404, { "Content-Type": "application/json" });',
      '    res.end(JSON.stringify({ error: "Not found" }));',
      "  } catch (error) {",
      "    console.error(error);",
      '    res.writeHead(500, { "Content-Type": "application/json" });',
      '    res.end(JSON.stringify({ error: "Internal server error" }));',
      "  }",
      "});",
      "",
      "server.listen(${2:3000}, () => {",
      '  console.log("Server listening on port ${2:3000}");',
      "});",
    ],
  },
  {
    key: "node-express-app",
    prefix: "nodeexp",
    description: "Node.js Express app bootstrap",
    languages: ["typescript", "javascript"],
    body: [
      'import express from "express";',
      "",
      "const app = express();",
      "app.use(express.json());",
      "",
      'app.get("${1:/health}", (_req, res) => {',
      "  res.json({ ok: true });",
      "});",
      "",
      "$0",
      "",
      "app.listen(${2:3000}, () => {",
      '  console.log("API listening on port ${2:3000}");',
      "});",
    ],
  },
  {
    key: "node-express-router",
    prefix: "nodeexpr",
    description: "Node.js Express router module",
    languages: ["typescript", "javascript"],
    body: [
      'import { Router } from "express";',
      "",
      "export const ${1:router} = Router();",
      "",
      '${1:router}.get("/", async (_req, res, next) => {',
      "  try {",
      "    $0",
      "    res.json({ ok: true });",
      "  } catch (error) {",
      "    next(error);",
      "  }",
      "});",
    ],
  },
  {
    key: "node-express-error-middleware",
    prefix: "nodeerr",
    description: "Node.js Express error handling middleware",
    languages: ["typescript", "javascript"],
    body: [
      "app.use((error, _req, res, _next) => {",
      "  console.error(error);",
      "  res.status(${1:500}).json({",
      '    error: error instanceof Error ? error.message : "Internal server error",',
      "  });",
      "});",
    ],
    variants: {
      typescript: {
        body: [
          'import type { ErrorRequestHandler } from "express";',
          "",
          "export const errorHandler: ErrorRequestHandler = (error, _req, res, _next) => {",
          "  console.error(error);",
          "  res.status(${1:500}).json({",
          '    error: error instanceof Error ? error.message : "Internal server error",',
          "  });",
          "};",
        ],
      },
    },
  },
  {
    key: "node-fastify-route",
    prefix: "nodefast",
    description: "Node.js Fastify route handler",
    languages: ["typescript", "javascript"],
    body: [
      'fastify.get("${1:/resource}", async (request, reply) => {',
      "  try {",
      "    $0",
      "    return reply.code(200).send({ ok: true });",
      "  } catch (error) {",
      "    request.log.error(error);",
      '    return reply.code(500).send({ error: "Internal server error" });',
      "  }",
      "});",
    ],
  },
  {
    key: "node-env-schema",
    prefix: "nodeenv",
    description: "Node.js typed environment variables with Zod",
    languages: ["typescript"],
    body: [
      'import { z } from "zod";',
      "",
      "const EnvSchema = z.object({",
      '  NODE_ENV: z.enum(["development", "test", "production"]),',
      "  PORT: z.coerce.number().int().positive().default(3000),",
      "  DATABASE_URL: z.string().url(),",
      "  $0",
      "});",
      "",
      "export const env = EnvSchema.parse(process.env);",
    ],
  },
  {
    key: "node-zod-validate-body",
    prefix: "nodezod",
    description: "Node.js Express Zod request body validation middleware",
    languages: ["typescript"],
    body: [
      'import type { RequestHandler } from "express";',
      "",
      "export const validate${1:Body}: RequestHandler = (req, res, next) => {",
      "  const parsed = ${2:Schema}.safeParse(req.body);",
      "",
      "  if (!parsed.success) {",
      "    res.status(400).json({ errors: parsed.error.flatten().fieldErrors });",
      "    return;",
      "  }",
      "",
      "  req.body = parsed.data;",
      "  next();",
      "};",
    ],
  },
  {
    key: "node-cors-middleware",
    prefix: "nodecors",
    description: "Node.js Express CORS middleware",
    languages: ["typescript", "javascript"],
    body: [
      "app.use((req, res, next) => {",
      '  res.setHeader("Access-Control-Allow-Origin", process.env.CORS_ORIGIN ?? "*");',
      '  res.setHeader("Access-Control-Allow-Methods", "GET,POST,PUT,PATCH,DELETE,OPTIONS");',
      '  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");',
      "",
      '  if (req.method === "OPTIONS") {',
      "    res.sendStatus(204);",
      "    return;",
      "  }",
      "",
      "  next();",
      "});",
    ],
  },
  {
    key: "node-process-signal",
    prefix: "nodesig",
    description: "Node.js graceful shutdown on SIGTERM",
    languages: ["typescript", "javascript"],
    body: [
      "function shutdown(signal) {",
      "  console.log(`Received ${signal}, shutting down...`);",
      "  $0",
      "  process.exit(0);",
      "}",
      "",
      'process.on("SIGTERM", () => shutdown("SIGTERM"));',
      'process.on("SIGINT", () => shutdown("SIGINT"));',
    ],
  },
  {
    key: "node-read-file-json",
    prefix: "nodejson",
    description: "Node.js read JSON file with fs/promises",
    languages: ["typescript", "javascript"],
    body: [
      'import { readFile } from "node:fs/promises";',
      "",
      'const raw = await readFile("${1:./data.json}", "utf8");',
      "const ${2:data} = JSON.parse(raw);",
      "$0",
    ],
    variants: {
      typescript: {
        body: [
          'import { readFile } from "node:fs/promises";',
          "",
          'const raw = await readFile("${1:./data.json}", "utf8");',
          "const ${2:data} = JSON.parse(raw) as ${3:DataType};",
          "$0",
        ],
      },
    },
  },
  {
    key: "node-api-response-helper",
    prefix: "nodeapi",
    description: "Node.js API JSON response helpers",
    languages: ["typescript", "javascript"],
    body: [
      "function jsonOk(data, status = 200) {",
      "  return Response.json({ ok: true, data }, { status });",
      "}",
      "",
      "function jsonError(message, status = 400) {",
      "  return Response.json({ ok: false, error: message }, { status });",
      "}",
    ],
  },
  {
    key: "node-web-crypto-hash",
    prefix: "nodehash",
    description: "Node.js Web Crypto SHA-256 hash",
    languages: ["typescript", "javascript"],
    body: [
      "const encoded = new TextEncoder().encode(${1:input});",
      'const digest = await crypto.subtle.digest("SHA-256", encoded);',
      "const ${2:hash} = Array.from(new Uint8Array(digest))",
      '  .map((byte) => byte.toString(16).padStart(2, "0"))',
      '  .join("");',
    ],
  },
  {
    key: "node-stream-pipeline",
    prefix: "nodepipe",
    description: "Node.js stream pipeline with error handling",
    languages: ["typescript", "javascript"],
    body: [
      'import { pipeline } from "node:stream/promises";',
      'import { createReadStream, createWriteStream } from "node:fs";',
      "",
      "await pipeline(",
      '  createReadStream("${1:input.txt}"),',
      '  createWriteStream("${2:output.txt}"),',
      ");",
    ],
  },
];
