// Synced from ES7+ React/Redux/React-Native extension — npm run snippets:sync

/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "others-anonymous-function",
    prefix: "anfn",
    description: "Creates an anonymous function · anfn",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "(${1:first}) => { ${2:second} }",
  },
  {
    key: "others-bind-this",
    prefix: "bnd",
    description: "Binds this to a method · bnd",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "this.${1:first} = this.${1:first}.bind(this)",
  },
  {
    key: "others-class-constructor",
    prefix: "rconst",
    description:
      "Adds a default constructor for it('', () => {})the class that contains props as arguments · rconst",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "constructor(props) {",
      "  super(props)",
      "",
      "  this.state = {",
      "     ${1:first}",
      "  }",
      "}",
    ],
  },
  {
    key: "others-comment-big-block",
    prefix: "cmmb",
    description: "Comment Big Block · cmmb",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: ["/**", " * ${1:first}", " */"],
  },
  {
    key: "others-component-did-mount",
    prefix: "cdm",
    description:
      "Invoked once, only on the client (not on the server), immediately after the initial rendering occurs. · cdm",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "componentDidMount() { ${1:first} }",
  },
  {
    key: "others-component-did-update",
    prefix: "cdup",
    description:
      "Invoked immediately after the component's updates are flushed to the DOM. · cdup",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "componentDidUpdate(prevProps, prevState) { ${1:first}} ",
  },
  {
    key: "others-component-props",
    prefix: "props",
    description: "Access component's props · props",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "this.props.${1:first}",
  },
  {
    key: "others-component-set-state-func",
    prefix: "ssf",
    description:
      "Performs a shallow merge of nextState into current state · ssf",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "this.setState((state, props) => { return { ${1:first} }})",
  },
  {
    key: "others-component-set-state-object",
    prefix: "sst",
    description:
      "Performs a shallow merge of nextState into current state · sst",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "this.setState({${1:first}})",
  },
  {
    key: "others-component-state",
    prefix: "state",
    description: "Component State · state",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "this.state.${1:first}",
  },
  {
    key: "others-component-will-unmount",
    prefix: "cwun",
    description:
      "Invoked immediately before a component is unmounted from the DOM. · cwun",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "componentWillUnmount() {${1:first} }",
  },
  {
    key: "others-create-context",
    prefix: "rcontext",
    description: "Create React context · rcontext",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "const ${1:first} = React.createContext()",
  },
  {
    key: "others-create-ref",
    prefix: "cref",
    description: "Create ref statement used inside constructor · cref",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "this.${1:first}Ref = React.createRef()",
  },
  {
    key: "others-destruct-props",
    prefix: "cp",
    description:
      "Creates and assigns a local variable using props destructing · cp",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "const { ${1:first} } = this.props",
  },
  {
    key: "others-destruct-state",
    prefix: "cs",
    description:
      "Creates and assigns a local variable using state destructing · cs",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "const { ${1:first} } = this.state",
  },
  {
    key: "others-destructing-array",
    prefix: "dar",
    description:
      "Creates and assigns a local variable using array destructing · dar",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "const [${2:second}] = ${1:first}",
  },
  {
    key: "others-destructing-object",
    prefix: "dob",
    description:
      "Creates and assigns a local variable using object destructing · dob",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "const {${2:second}} = ${1:first}",
  },
  {
    key: "others-empty-state",
    prefix: "est",
    description:
      "Creates empty state object. To be used in a constructor. · est",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "state = { ${1:first} }",
  },
  {
    key: "others-export-as",
    prefix: "exa",
    description: "Export As · exa",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "export { ${2:second} as ${3:third} } from '${1:first}'",
  },
  {
    key: "others-export-default",
    prefix: "exp",
    description: "Export Default · exp",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "export default ${1:first}",
  },
  {
    key: "others-export-default-function",
    prefix: "edf",
    description: "Export default function · edf",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "export default (${1:first}) => {${2:second}}",
  },
  {
    key: "others-export-default-named-function",
    prefix: "ednf",
    description: "Export default named function · ednf",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "export default function ${1:first}(${2:second}) {${3:third}}",
  },
  {
    key: "others-export-destructing",
    prefix: "exd",
    description: "Export Destructing · exd",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "export { ${2:second} } from '${1:first}'",
  },
  {
    key: "others-export-named-function",
    prefix: "enf",
    description: "Export named function · enf",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "export const ${1:first} = (${2:second}) => {${3:third}}",
  },
  {
    key: "others-for-each",
    prefix: "fre",
    description: "Creates a forEach statement · fre",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "${1:first}.forEach(${2:second} => {${3:third}})",
  },
  {
    key: "others-for-in",
    prefix: "fin",
    description: "Iterating over property values of iterable objects · fin",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "for(let ${1:first} in ${2:second}) {${3:third}}",
  },
  {
    key: "others-for-of",
    prefix: "fof",
    description: "Iterating over property names of iterable objects · fof",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "for(let ${1:first} of ${2:second}) {${3:third}}",
  },
  {
    key: "others-get-derived-state-from-props",
    prefix: "gdsfp",
    description:
      "Invoked right before calling the render method, both on the initial mount and on subsequent updates. · gdsfp",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "static getDerivedStateFromProps(props, state) {${1:first}}",
  },
  {
    key: "others-get-snapshot-before-update",
    prefix: "gsbu",
    description:
      "Called right before mutations are made (e.g. before the DOM is updated) · gsbu",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "getSnapshotBeforeUpdate = (prevProps, prevState) => {${1:first}}",
  },
  {
    key: "others-hoc-component",
    prefix: "hoc",
    description: "Hoc Component · hoc",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "import React from 'react'",
      "import PropTypes from 'prop-types'",
      "",
      "export default (WrappedComponent) => {",
      "  const hocComponent = ({ ...props }) => <WrappedComponent {...props} />",
      "",
      "  hocComponent.propTypes = {}",
      "",
      "  return hocComponent",
      "}",
      "",
    ],
  },
  {
    key: "others-hoc-component-with-redux",
    prefix: "hocredux",
    description: "Hoc Component With Redux · hocredux",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "import React from 'react'",
      "import { connect } from 'react-redux'",
      "import PropTypes from 'prop-types'",
      "",
      "export const mapStateToProps = state => ({})",
      "",
      "export const mapDispatchToProps = {}",
      "",
      "export const ${1:first} = (WrappedComponent) => {",
      "  const hocComponent = ({ ...props }) => <WrappedComponent {...props} />",
      "",
      "  hocComponent.propTypes = {}",
      "",
      "  return hocComponent",
      "}",
      "",
      "export default WrapperComponent => connect(mapStateToProps, mapDispatchToProps)(${1:first}(WrapperComponent))",
      "",
    ],
  },
  {
    key: "others-method",
    prefix: "met",
    description: "Creates a method inside a class · met",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "${1:first} = (${2:second}) => {${3:third}}",
  },
  {
    key: "others-named-function",
    prefix: "nfn",
    description: "Creates a named function · nfn",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "const ${1:first} = (${2:second}) => { ${3:third} }",
  },
  {
    key: "others-promise",
    prefix: "prom",
    description:
      "Creates and returns a new Promise in the standard ES7 syntax · prom",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "return new Promise((resolve, reject) => { ${1:first} })",
  },
  {
    key: "others-property-get",
    prefix: "pge",
    description: "Creates a getter property inside a class · pge",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: ["get ${1:first}() {", "  return this.${2:second}", "}"],
  },
  {
    key: "others-property-set",
    prefix: "pse",
    description: "Creates a setter property inside a class · pse",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "set ${1:first}(${2:second}) {${3:third}}",
  },
  {
    key: "others-set-interval",
    prefix: "sti",
    description: "Executes the given function at specified intervals · sti",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "setInterval(() => { ${1:first} }, ${2:second})",
  },
  {
    key: "others-set-time-out",
    prefix: "sto",
    description: "Executes the given function after the specified delay · sto",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "setTimeout(() => { ${1:first} }, ${2:second})",
  },
  {
    key: "others-should-component-update",
    prefix: "scu",
    description:
      "Invoked before rendering when new props or state are being received. · scu",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "shouldComponentUpdate(nextProps, nextState) { ${1:first} }",
  },
  {
    key: "others-typeof-snippet",
    prefix: "tpf",
    description: "Typeof Snippet · tpf",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "typeof ${1:first}",
  },
];
