// Synced from ES7+ React/Redux/React-Native extension — npm run snippets:sync

/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "propTypes-prop-type-any",
    prefix: "ptany",
    description: "Any prop type · ptany",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.any",
  },
  {
    key: "propTypes-prop-type-array",
    prefix: "pta",
    description: "Array prop type · pta",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.array",
  },
  {
    key: "propTypes-prop-type-array-of",
    prefix: "ptao",
    description: "An array of a certain type · ptao",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.arrayOf($0)",
  },
  {
    key: "propTypes-prop-type-array-of-required",
    prefix: "ptaor",
    description: "An array of a certain type required · ptaor",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.arrayOf($0).isRequired",
  },
  {
    key: "propTypes-prop-type-array-required",
    prefix: "ptar",
    description: "Array prop type required · ptar",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.array.isRequired",
  },
  {
    key: "propTypes-prop-type-bool",
    prefix: "ptb",
    description: "Bool prop type · ptb",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.bool",
  },
  {
    key: "propTypes-prop-type-bool-required",
    prefix: "ptbr",
    description: "Bool prop type required · ptbr",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.bool.isRequired",
  },
  {
    key: "propTypes-prop-type-element",
    prefix: "ptel",
    description: "React element prop type · ptel",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.element",
  },
  {
    key: "propTypes-prop-type-element-required",
    prefix: "ptelr",
    description: "React element prop type required · ptelr",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.element.isRequired",
  },
  {
    key: "propTypes-prop-type-enum",
    prefix: "pte",
    description:
      "Prop type limited to specific values by treating it as an enum · pte",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.oneOf(['$0'])",
  },
  {
    key: "propTypes-prop-type-enum-required",
    prefix: "pter",
    description:
      "Prop type limited to specific values by treating it as an enum required · pter",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.oneOf(['$0']).isRequired",
  },
  {
    key: "propTypes-prop-type-exact",
    prefix: "ptex",
    description: "An object with warnings on extra properties · ptex",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: ["PropTypes.exact({", "  $0", "})"],
  },
  {
    key: "propTypes-prop-type-exact-required",
    prefix: "ptexr",
    description: "An object with warnings on extra properties required · ptexr",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: ["PropTypes.exact({", "  $0", "}).isRequired"],
  },
  {
    key: "propTypes-prop-type-func",
    prefix: "ptf",
    description: "Func prop type · ptf",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.func",
  },
  {
    key: "propTypes-prop-type-func-required",
    prefix: "ptfr",
    description: "Func prop type required · ptfr",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.func.isRequired",
  },
  {
    key: "propTypes-prop-type-instance-of",
    prefix: "pti",
    description: "Is an instance of a class prop type · pti",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.instanceOf($0)",
  },
  {
    key: "propTypes-prop-type-instance-of-required",
    prefix: "ptir",
    description: "Is an instance of a class prop type required · ptir",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.instanceOf($0).isRequired",
  },
  {
    key: "propTypes-prop-type-node",
    prefix: "ptnd",
    description:
      "Anything that can be rendered: numbers, strings, elements or an array · ptnd",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.node",
  },
  {
    key: "propTypes-prop-type-node-required",
    prefix: "ptndr",
    description:
      "Anything that can be rendered: numbers, strings, elements or an array required · ptndr",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.node.isRequired",
  },
  {
    key: "propTypes-prop-type-number",
    prefix: "ptn",
    description: "Number prop type · ptn",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.number",
  },
  {
    key: "propTypes-prop-type-number-required",
    prefix: "ptnr",
    description: "Number prop type required · ptnr",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.number.isRequired",
  },
  {
    key: "propTypes-prop-type-object",
    prefix: "pto",
    description: "Object prop type · pto",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.object",
  },
  {
    key: "propTypes-prop-type-object-of",
    prefix: "ptoo",
    description: "An object with property values of a certain type · ptoo",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.objectOf($0)",
  },
  {
    key: "propTypes-prop-type-object-of-required",
    prefix: "ptoor",
    description:
      "An object with property values of a certain type required · ptoor",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.objectOf($0).isRequired",
  },
  {
    key: "propTypes-prop-type-object-required",
    prefix: "ptor",
    description: "Object prop type required · ptor",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.object.isRequired",
  },
  {
    key: "propTypes-prop-type-one-of-type",
    prefix: "ptet",
    description: "An object that could be one of many types · ptet",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: ["PropTypes.oneOfType([", "  $0", "])"],
  },
  {
    key: "propTypes-prop-type-one-of-type-required",
    prefix: "ptetr",
    description: "An object that could be one of many types required · ptetr",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: ["PropTypes.oneOfType([", "  $0", "]).isRequired"],
  },
  {
    key: "propTypes-prop-type-shape",
    prefix: "ptsh",
    description: "An object taking on a particular shape · ptsh",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: ["PropTypes.shape({", "  $0", "})"],
  },
  {
    key: "propTypes-prop-type-shape-required",
    prefix: "ptshr",
    description: "An object taking on a particular shape required · ptshr",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: ["PropTypes.shape({", "  $0", "}).isRequired"],
  },
  {
    key: "propTypes-prop-type-string",
    prefix: "pts",
    description: "String prop type · pts",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.string",
  },
  {
    key: "propTypes-prop-type-string-required",
    prefix: "ptsr",
    description: "String prop type required · ptsr",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "PropTypes.string.isRequired",
  },
];
