/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "react-use-state",
    prefix: "usestate",
    description: "React useState hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: "const [${1:state}, set${1/(.*)/${1:/capitalize}/}] = useState(${2:initial});",
    variants: {
      typescriptreact: {
        body: "const [${1:state}, set${1/(.*)/${1:/capitalize}/}] = useState<${2:string} | null>(${3:null});",
      },
    },
  },
  {
    key: "react-use-effect",
    prefix: "useeffect",
    description: "React useEffect hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "useEffect(() => {",
      "  $0",
      "}, [${1:dependencies}]);",
    ],
  },
  {
    key: "react-use-effect-cleanup",
    prefix: "useeffectcl",
    description: "React useEffect with cleanup",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "useEffect(() => {",
      "  $1",
      "",
      "  return () => {",
      "    $0",
      "  };",
      "}, [${2:dependencies}]);",
    ],
  },
  {
    key: "react-use-callback",
    prefix: "usecallback",
    description: "React useCallback hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "const ${1:handler} = useCallback((${2:args}) => {",
      "  $0",
      "}, [${3:dependencies}]);",
    ],
    variants: {
      typescriptreact: {
        body: [
          "const ${1:handler} = useCallback((${2:args}: ${4:ArgsType}) => {",
          "  $0",
          "}, [${3:dependencies}]);",
        ],
      },
    },
  },
  {
    key: "react-use-memo",
    prefix: "usememo",
    description: "React useMemo hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "const ${1:value} = useMemo(() => {",
      "  return $0;",
      "}, [${2:dependencies}]);",
    ],
    variants: {
      typescriptreact: {
        body: [
          "const ${1:value} = useMemo<${3:Type}>(() => {",
          "  return $0;",
          "}, [${2:dependencies}]);",
        ],
      },
    },
  },
  {
    key: "react-use-ref",
    prefix: "useref",
    description: "React useRef hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: "const ${1:ref} = useRef(${2:null});",
    variants: {
      typescriptreact: {
        body: "const ${1:ref} = useRef<${2:HTMLDivElement} | null>(null);",
      },
    },
  },
  {
    key: "react-use-reducer",
    prefix: "usereducer",
    description: "React useReducer hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: "const [${1:state}, ${2:dispatch}] = useReducer(${3:reducer}, ${4:initialState});",
    variants: {
      typescriptreact: {
        body: "const [${1:state}, ${2:dispatch}] = useReducer<${5:State}, ${6:Action}>(${3:reducer}, ${4:initialState});",
      },
    },
  },
  {
    key: "react-reducer-function",
    prefix: "reducer",
    description: "React reducer function with action types",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "function ${1:feature}Reducer(state, action) {",
      "  switch (action.type) {",
      "    case \"${2:SET_VALUE}\":",
      "      return { ...state, ${3:value}: action.payload };",
      "    default:",
      "      return state;",
      "  }",
      "}",
    ],
    variants: {
      typescriptreact: {
        body: [
          "type ${1:Feature}State = {",
          "  ${2:value}: string;",
          "};",
          "",
          "type ${1:Feature}Action =",
          "  | { type: \"SET_VALUE\"; payload: string }",
          "  | { type: \"RESET\" };",
          "",
          "function ${1:feature}Reducer(state: ${1:Feature}State, action: ${1:Feature}Action): ${1:Feature}State {",
          "  switch (action.type) {",
          "    case \"SET_VALUE\":",
          "      return { ...state, ${2:value}: action.payload };",
          "    case \"RESET\":",
          "      return { ${2:value}: \"\" };",
          "    default:",
          "      return state;",
          "  }",
          "}",
        ],
      },
    },
  },
  {
    key: "react-use-context",
    prefix: "usecontext",
    description: "React useContext hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: "const ${1:context} = useContext(${2:Context});",
  },
  {
    key: "react-use-layout-effect",
    prefix: "uselayouteffect",
    description: "React useLayoutEffect hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "useLayoutEffect(() => {",
      "  $0",
      "}, [${1:dependencies}]);",
    ],
  },
  {
    key: "react-use-imperative-handle",
    prefix: "useimperativehandle",
    description: "React useImperativeHandle hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "useImperativeHandle(ref, () => ({",
      "  ${1:focus}: () => {",
      "    $0",
      "  },",
      "}), [${2:dependencies}]);",
    ],
  },
  {
    key: "react-use-id",
    prefix: "useid",
    description: "React useId hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: "const ${1:id} = useId();",
  },
  {
    key: "react-use-deferred-value",
    prefix: "usedeferredvalue",
    description: "React useDeferredValue hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: "const ${1:deferredValue} = useDeferredValue(${2:value});",
  },
  {
    key: "react-use-transition",
    prefix: "usetransition",
    description: "React useTransition hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "const [${1:isPending}, ${2:startTransition}] = useTransition();",
      "",
      "${2:startTransition}(() => {",
      "  $0",
      "});",
    ],
  },
  {
    key: "react-use-action-state",
    prefix: "useactionstate",
    description: "React useActionState hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "const [${1:state}, ${2:formAction}, ${3:isPending}] = useActionState(${4:action}, ${5:initialState});",
    ],
    variants: {
      typescriptreact: {
        body: [
          "const [${1:state}, ${2:formAction}, ${3:isPending}] = useActionState<${6:State}, ${7:FormData}>(",
          "  ${4:action},",
          "  ${5:initialState},",
          ");",
        ],
      },
    },
  },
  {
    key: "react-use-hook",
    prefix: "use",
    description: "React use() for promises and context",
    languages: ["javascriptreact", "typescriptreact"],
    body: "const ${1:value} = use(${2:promiseOrContext});",
  },
  {
    key: "react-custom-hook",
    prefix: "usehook",
    description: "React custom hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "export function use${1:Hook}(${2:params}) {",
      "  $0",
      "  return ${3:value};",
      "}",
    ],
    variants: {
      typescriptreact: {
        body: [
          "export function use${1:Hook}(${2:params}: ${4:ParamsType}): ${5:ReturnType} {",
          "  $0",
          "  return ${3:value};",
          "}",
        ],
      },
    },
  },
  {
    key: "react-use-debounce",
    prefix: "usedebounce",
    description: "React useDebounce custom hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "export function useDebounce(${1:value}, ${2:delayMs} = 300) {",
      "  const [debouncedValue, setDebouncedValue] = useState(${1:value});",
      "",
      "  useEffect(() => {",
      "    const timer = window.setTimeout(() => setDebouncedValue(${1:value}), ${2:delayMs});",
      "    return () => window.clearTimeout(timer);",
      "  }, [${1:value}, ${2:delayMs}]);",
      "",
      "  return debouncedValue;",
      "}",
    ],
    variants: {
      typescriptreact: {
        body: [
          "export function useDebounce<T>(${1:value}: T, ${2:delayMs} = 300): T {",
          "  const [debouncedValue, setDebouncedValue] = useState(${1:value});",
          "",
          "  useEffect(() => {",
          "    const timer = window.setTimeout(() => setDebouncedValue(${1:value}), ${2:delayMs});",
          "    return () => window.clearTimeout(timer);",
          "  }, [${1:value}, ${2:delayMs}]);",
          "",
          "  return debouncedValue;",
          "}",
        ],
      },
    },
  },
  {
    key: "react-use-local-storage",
    prefix: "uselocalstorage",
    description: "React useLocalStorage custom hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "export function useLocalStorage(${1:key}, ${2:initialValue}) {",
      "  const [value, setValue] = useState(() => {",
      "    try {",
      "      const stored = window.localStorage.getItem(${1:key});",
      "      return stored ? JSON.parse(stored) : ${2:initialValue};",
      "    } catch {",
      "      return ${2:initialValue};",
      "    }",
      "  });",
      "",
      "  useEffect(() => {",
      "    window.localStorage.setItem(${1:key}, JSON.stringify(value));",
      "  }, [${1:key}, value]);",
      "",
      "  return [value, setValue];",
      "}",
    ],
    variants: {
      typescriptreact: {
        body: [
          "export function useLocalStorage<T>(${1:key}: string, ${2:initialValue}: T): [T, React.Dispatch<React.SetStateAction<T>>] {",
          "  const [value, setValue] = useState<T>(() => {",
          "    try {",
          "      const stored = window.localStorage.getItem(${1:key});",
          "      return stored ? (JSON.parse(stored) as T) : ${2:initialValue};",
          "    } catch {",
          "      return ${2:initialValue};",
          "    }",
          "  });",
          "",
          "  useEffect(() => {",
          "    window.localStorage.setItem(${1:key}, JSON.stringify(value));",
          "  }, [${1:key}, value]);",
          "",
          "  return [value, setValue];",
          "}",
        ],
      },
    },
  },
  {
    key: "react-use-media-query",
    prefix: "usemediaquery",
    description: "React useMediaQuery custom hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "export function useMediaQuery(${1:query}) {",
      "  const [matches, setMatches] = useState(() => window.matchMedia(${1:query}).matches);",
      "",
      "  useEffect(() => {",
      "    const mediaQuery = window.matchMedia(${1:query});",
      "    const handler = (event) => setMatches(event.matches);",
      "",
      "    mediaQuery.addEventListener(\"change\", handler);",
      "    return () => mediaQuery.removeEventListener(\"change\", handler);",
      "  }, [${1:query}]);",
      "",
      "  return matches;",
      "}",
    ],
    variants: {
      typescriptreact: {
        body: [
          "export function useMediaQuery(${1:query}: string): boolean {",
          "  const [matches, setMatches] = useState(() => window.matchMedia(${1:query}).matches);",
          "",
          "  useEffect(() => {",
          "    const mediaQuery = window.matchMedia(${1:query});",
          "    const handler = (event: MediaQueryListEvent) => setMatches(event.matches);",
          "",
          "    mediaQuery.addEventListener(\"change\", handler);",
          "    return () => mediaQuery.removeEventListener(\"change\", handler);",
          "  }, [${1:query}]);",
          "",
          "  return matches;",
          "}",
        ],
      },
    },
  },
  {
    key: "react-use-sync-external-store",
    prefix: "usesyncexternalstore",
    description: "React useSyncExternalStore hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "const ${1:snapshot} = useSyncExternalStore(",
      "  ${2:subscribe},",
      "  ${3:getSnapshot},",
      "  ${4:getServerSnapshot},",
      ");",
    ],
  },
  {
    key: "react-use-form-status",
    prefix: "useformstatus",
    description: "React useFormStatus for pending form state",
    languages: ["javascriptreact", "typescriptreact"],
    body: "const { pending, data, method, action } = useFormStatus();",
  },
  {
    key: "react-use-optimistic",
    prefix: "useoptimistic",
    description: "React useOptimistic hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "const [${1:optimisticState}, ${2:addOptimistic}] = useOptimistic(",
      "  ${3:state},",
      "  (current, ${4:update}) => ${5:mergeUpdate(current, update)},",
      ");",
    ],
    variants: {
      typescriptreact: {
        body: [
          "const [${1:optimisticState}, ${2:addOptimistic}] = useOptimistic<${6:State}, ${7:Update}>(",
          "  ${3:state},",
          "  (current, ${4:update}) => ${5:mergeUpdate(current, update)},",
          ");",
        ],
      },
    },
  },
  {
    key: "react-use-online-status",
    prefix: "useonline",
    description: "React useOnlineStatus custom hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "export function useOnlineStatus() {",
      "  const [isOnline, setIsOnline] = useState(() => navigator.onLine);",
      "",
      "  useEffect(() => {",
      "    const handleOnline = () => setIsOnline(true);",
      "    const handleOffline = () => setIsOnline(false);",
      "",
      "    window.addEventListener(\"online\", handleOnline);",
      "    window.addEventListener(\"offline\", handleOffline);",
      "",
      "    return () => {",
      "      window.removeEventListener(\"online\", handleOnline);",
      "      window.removeEventListener(\"offline\", handleOffline);",
      "    };",
      "  }, []);",
      "",
      "  return isOnline;",
      "}",
    ],
  },
  {
    key: "react-use-intersection-observer",
    prefix: "useinview",
    description: "React useIntersectionObserver custom hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "export function useIntersectionObserver(${1:options} = {}) {",
      "  const ref = useRef(null);",
      "  const [isIntersecting, setIsIntersecting] = useState(false);",
      "",
      "  useEffect(() => {",
      "    const element = ref.current;",
      "    if (!element) return;",
      "",
      "    const observer = new IntersectionObserver(([entry]) => {",
      "      setIsIntersecting(entry.isIntersecting);",
      "    }, ${1:options});",
      "",
      "    observer.observe(element);",
      "    return () => observer.disconnect();",
      "  }, [${1:options}]);",
      "",
      "  return { ref, isIntersecting };",
      "}",
    ],
    variants: {
      typescriptreact: {
        body: [
          "export function useIntersectionObserver(",
          "  options: IntersectionObserverInit = {},",
          ") {",
          "  const ref = useRef<HTMLElement | null>(null);",
          "  const [isIntersecting, setIsIntersecting] = useState(false);",
          "",
          "  useEffect(() => {",
          "    const element = ref.current;",
          "    if (!element) return;",
          "",
          "    const observer = new IntersectionObserver(([entry]) => {",
          "      setIsIntersecting(entry.isIntersecting);",
          "    }, options);",
          "",
          "    observer.observe(element);",
          "    return () => observer.disconnect();",
          "  }, [options]);",
          "",
          "  return { ref, isIntersecting };",
          "}",
        ],
      },
    },
  },
  {
    key: "react-use-event-listener",
    prefix: "useeventlistener",
    description: "React useEventListener custom hook",
    languages: ["javascriptreact", "typescriptreact"],
    body: [
      "export function useEventListener(${1:eventName}, ${2:handler}, ${3:element} = window) {",
      "  const savedHandler = useRef(${2:handler});",
      "",
      "  useEffect(() => {",
      "    savedHandler.current = ${2:handler};",
      "  }, [${2:handler}]);",
      "",
      "  useEffect(() => {",
      "    if (!${3:element}) return;",
      "",
      "    const listener = (event) => savedHandler.current(event);",
      "    ${3:element}.addEventListener(${1:eventName}, listener);",
      "    return () => ${3:element}.removeEventListener(${1:eventName}, listener);",
      "  }, [${1:eventName}, ${3:element}]);",
      "}",
    ],
    variants: {
      typescriptreact: {
        body: [
          "export function useEventListener<K extends keyof WindowEventMap>(",
          "  ${1:eventName}: K,",
          "  ${2:handler}: (event: WindowEventMap[K]) => void,",
          "  ${3:element}: Window | HTMLElement | null = window,",
          ") {",
          "  const savedHandler = useRef(${2:handler});",
          "",
          "  useEffect(() => {",
          "    savedHandler.current = ${2:handler};",
          "  }, [${2:handler}]);",
          "",
          "  useEffect(() => {",
          "    if (!${3:element}) return;",
          "",
          "    const listener = (event: WindowEventMap[K]) => savedHandler.current(event);",
          "    ${3:element}.addEventListener(${1:eventName}, listener as EventListener);",
          "    return () => ${3:element}.removeEventListener(${1:eventName}, listener as EventListener);",
          "  }, [${1:eventName}, ${3:element}]);",
          "}",
        ],
      },
    },
  },
];
