/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "next-server-action",
    prefix: "nxaction",
    description: "Next.js server action with validation",
    languages: ["typescript"],
    body: [
      '"use server";',
      "",
      'import { revalidatePath } from "next/cache";',
      "",
      "export async function ${1:actionName}(formData: FormData) {",
      "  const ${2:payload} = {",
      '    ${3:field}: formData.get("${3:field}")?.toString() ?? "",',
      "  };",
      "",
      "  $0",
      "",
      '  revalidatePath("${4:/}");',
      "  return { ok: true as const };",
      "}",
    ],
  },
  {
    key: "next-page-component",
    prefix: "nxpage",
    description: "Next.js App Router page component",
    languages: ["typescriptreact", "javascriptreact"],
    body: [
      "export default async function ${1:Page}() {",
      "  const ${2:data} = await ${3:fetchData}();",
      "",
      "  return (",
      "    <main>",
      "      <h1>${4:Page title}</h1>",
      "      $0",
      "    </main>",
      "  );",
      "}",
    ],
    variants: {
      typescriptreact: {
        body: [
          "export default async function ${1:Page}() {",
          "  const ${2:data}: ${5:DataType} = await ${3:fetchData}();",
          "",
          "  return (",
          "    <main>",
          "      <h1>${4:Page title}</h1>",
          "      $0",
          "    </main>",
          "  );",
          "}",
        ],
      },
    },
  },
  {
    key: "next-layout-component",
    prefix: "nxlayout",
    description: "Next.js App Router layout component",
    languages: ["typescriptreact", "javascriptreact"],
    body: [
      "export default function ${1:Layout}({ children }) {",
      "  return (",
      '    <div className="${2:layout}">',
      "      $0",
      "      {children}",
      "    </div>",
      "  );",
      "}",
    ],
    variants: {
      typescriptreact: {
        body: [
          'import type { ReactNode } from "react";',
          "",
          "export default function ${1:Layout}({ children }: { children: ReactNode }) {",
          "  return (",
          '    <div className="${2:layout}">',
          "      $0",
          "      {children}",
          "    </div>",
          "  );",
          "}",
        ],
      },
    },
  },
  {
    key: "next-loading-ui",
    prefix: "nxloading",
    description: "Next.js loading UI segment",
    languages: ["typescriptreact", "javascriptreact"],
    body: [
      "export default function Loading() {",
      "  return (",
      '    <div role="status" aria-live="polite" className="${1:loading}">',
      "      Loading...",
      "    </div>",
      "  );",
      "}",
    ],
  },
  {
    key: "next-error-ui",
    prefix: "nxerror",
    description: "Next.js error boundary UI segment",
    languages: ["typescriptreact", "javascriptreact"],
    body: [
      '"use client";',
      "",
      "export default function Error({",
      "  error,",
      "  reset,",
      "}) {",
      "  return (",
      '    <div role="alert" className="${1:error}">',
      "      <h2>Something went wrong</h2>",
      "      <p>{error.message}</p>",
      '      <button type="button" onClick={() => reset()}>',
      "        Try again",
      "      </button>",
      "    </div>",
      "  );",
      "}",
    ],
    variants: {
      typescriptreact: {
        body: [
          '"use client";',
          "",
          "export default function Error({",
          "  error,",
          "  reset,",
          "}: {",
          "  error: Error & { digest?: string };",
          "  reset: () => void;",
          "}) {",
          "  return (",
          '    <div role="alert" className="${1:error}">',
          "      <h2>Something went wrong</h2>",
          "      <p>{error.message}</p>",
          '      <button type="button" onClick={() => reset()}>',
          "        Try again",
          "      </button>",
          "    </div>",
          "  );",
          "}",
        ],
      },
    },
  },
  {
    key: "next-route-handler-get",
    prefix: "nxget",
    description: "Next.js route handler GET",
    languages: ["typescript", "javascript"],
    body: [
      "export async function GET(request: Request) {",
      "  try {",
      "    $0",
      "    return Response.json({ ok: true });",
      "  } catch (error) {",
      "    console.error(error);",
      '    return Response.json({ error: "Internal server error" }, { status: 500 });',
      "  }",
      "}",
    ],
    variants: {
      javascript: {
        body: [
          "export async function GET(request) {",
          "  try {",
          "    $0",
          "    return Response.json({ ok: true });",
          "  } catch (error) {",
          "    console.error(error);",
          '    return Response.json({ error: "Internal server error" }, { status: 500 });',
          "  }",
          "}",
        ],
      },
    },
  },
  {
    key: "next-route-handler-post",
    prefix: "nxpost",
    description: "Next.js route handler POST with JSON body",
    languages: ["typescript", "javascript"],
    body: [
      "export async function POST(request: Request) {",
      "  try {",
      "    const body = await request.json();",
      "    $0",
      "    return Response.json({ ok: true }, { status: 201 });",
      "  } catch (error) {",
      "    console.error(error);",
      '    return Response.json({ error: "Invalid request" }, { status: 400 });',
      "  }",
      "}",
    ],
    variants: {
      javascript: {
        body: [
          "export async function POST(request) {",
          "  try {",
          "    const body = await request.json();",
          "    $0",
          "    return Response.json({ ok: true }, { status: 201 });",
          "  } catch (error) {",
          "    console.error(error);",
          '    return Response.json({ error: "Invalid request" }, { status: 400 });',
          "  }",
          "}",
        ],
      },
    },
  },
  {
    key: "next-metadata",
    prefix: "nxmeta",
    description: "Next.js page metadata export",
    languages: ["typescript"],
    body: [
      'import type { Metadata } from "next";',
      "",
      "export const metadata: Metadata = {",
      '  title: "${1:Page title}",',
      '  description: "${2:Page description}",',
      "  openGraph: {",
      '    title: "${1:Page title}",',
      '    description: "${2:Page description}",',
      "  },",
      "};",
    ],
  },
  {
    key: "next-middleware",
    prefix: "nxmw",
    description: "Next.js middleware matcher",
    languages: ["typescript", "javascript"],
    body: [
      'import { NextResponse } from "next/server";',
      'import type { NextRequest } from "next/server";',
      "",
      "export function middleware(request: NextRequest) {",
      "  $0",
      "  return NextResponse.next();",
      "}",
      "",
      "export const config = {",
      '  matcher: ["${1:/dashboard/:path*}"],',
      "};",
    ],
    variants: {
      javascript: {
        body: [
          'import { NextResponse } from "next/server";',
          "",
          "export function middleware(request) {",
          "  $0",
          "  return NextResponse.next();",
          "}",
          "",
          "export const config = {",
          '  matcher: ["${1:/dashboard/:path*}"],',
          "};",
        ],
      },
    },
  },
  {
    key: "next-revalidate-path",
    prefix: "nxreval",
    description: "Next.js revalidatePath cache invalidation",
    languages: ["typescript", "javascript"],
    body: [
      'import { revalidatePath } from "next/cache";',
      "",
      'revalidatePath("${1:/path}");',
    ],
  },
  {
    key: "next-redirect",
    prefix: "nxredirect",
    description: "Next.js redirect in server component or action",
    languages: ["typescript", "javascript"],
    body: [
      'import { redirect } from "next/navigation";',
      "",
      'redirect("${1:/destination}");',
    ],
  },
  {
    key: "next-generate-static-params",
    prefix: "nxparams",
    description: "Next.js generateStaticParams for dynamic routes",
    languages: ["typescript", "javascript"],
    body: [
      "export async function generateStaticParams() {",
      "  const ${1:items} = await ${2:fetchItems}();",
      "",
      "  return ${1:items}.map((${3:item}) => ({",
      "    ${4:slug}: ${3:item}.${4:slug},",
      "  }));",
      "}",
    ],
  },
];
