// Synced from ES7+ React/Redux/React-Native extension (vendored in-repo)

/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "redux-import-redux-connect",
    prefix: "redux",
    description: "Import Redux Connect · redux",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "import { connect } from 'react-redux'",
  },
  {
    key: "redux-mapping-to-props",
    prefix: "reduxmap",
    description: "Mapping To Props · reduxmap",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "const mapStateToProps = (state) => ({})",
      "",
      "const mapDispatchToProps = {}",
    ],
  },
  {
    key: "redux-redux-action",
    prefix: "rxaction",
    description: "Redux Action · rxaction",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "export const ${1:first} = (payload) => ({",
      "  type: ${2:second},",
      "  payload",
      "})",
      "",
    ],
  },
  {
    key: "redux-redux-const",
    prefix: "rxconst",
    description: "Redux Const · rxconst",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "export const ${1:first} = '${1:first}'",
  },
  {
    key: "redux-redux-reducer",
    prefix: "rxreducer",
    description: "Redux Reducer · rxreducer",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "const initialState = {}",
      "",
      "export default (state = initialState, { type, payload }) => {",
      "  switch (type) {",
      "",
      "  case ${1:first}:",
      "    return { ...state, ...payload }",
      "",
      "  default:",
      "    return state",
      "  }",
      "}",
      "",
    ],
  },
  {
    key: "redux-redux-selector",
    prefix: "rxselect",
    description: "Redux Selector · rxselect",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "import { createSelector } from 'reselect'",
      "",
      "export const ${1:first} = state => state.${2:second}",
    ],
  },
  {
    key: "redux-redux-slice",
    prefix: "rxslice",
    description: "Redux Slice · rxslice",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "import { createSlice } from '@reduxjs/toolkit'",
      "",
      "const initialState = {",
      "",
      "}",
      "",
      "const ${1:${TM_FILENAME_BASE}} = createSlice({",
      "  name: ${2:second},",
      "  initialState,",
      "  reducers: {}",
      "});",
      "",
      "export const {} = ${1:${TM_FILENAME_BASE}}.actions",
      "",
      "export default ${1:${TM_FILENAME_BASE}}.reducer",
    ],
  },
];
