// Synced from ES7+ React/Redux/React-Native extension — npm run snippets:sync

/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "tests-describe-block",
    prefix: "desc",
    description: "Testing `describe` block · desc",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "describe('${1:first}', () => { ${2:second} })",
  },
  {
    key: "tests-it-async-block",
    prefix: "tita",
    description: "Testing asynchronous `it` block · tita",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "it('should ${1:first}', async () => { ${2:second} })",
  },
  {
    key: "tests-it-block",
    prefix: "tit",
    description: "Testing `it` block · tit",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "it('should ${1:first}', () => { ${2:second} })",
  },
  {
    key: "tests-setup-react-component-test-with-redux",
    prefix: "srtest",
    description: "Create test component · srtest",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "import React from 'react'",
      "import renderer from 'react-test-renderer'",
      "import { Provider } from 'react-redux'",
      "",
      "import store from '~/store'",
      "import { ${1:${TM_FILENAME_BASE}} } from '../${1:${TM_FILENAME_BASE}}'",
      "",
      "describe('<${1:${TM_FILENAME_BASE}} />', () => {",
      "  const defaultProps = {}",
      "  const wrapper = renderer.create(",
      "    <Provider store={store}>",
      "     <${1:${TM_FILENAME_BASE}} {...defaultProps} />",
      "    </Provider>,",
      "  )",
      "",
      "  test('render', () => {",
      "    expect(wrapper).toMatchSnapshot()",
      "  })",
      "})",
    ],
  },
  {
    key: "tests-setup-react-native-test",
    prefix: "sntest",
    description: "Setup React Native Test · sntest",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "import 'react-native'",
      "import React from 'react'",
      "import renderer from 'react-test-renderer'",
      "",
      "import ${1:${TM_FILENAME_BASE}} from '../${1:${TM_FILENAME_BASE}}'",
      "",
      "describe('<${1:${TM_FILENAME_BASE}} />', () => {",
      "  const defaultProps = {}",
      "  const wrapper = renderer.create(<${1:${TM_FILENAME_BASE}} {...defaultProps} />)",
      "",
      "  test('render', () => {",
      "    expect(wrapper).toMatchSnapshot()",
      "  })",
      "})",
    ],
  },
  {
    key: "tests-setup-react-native-test-with-redux",
    prefix: "snrtest",
    description: "Setup React Native Test With Redux · snrtest",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "import 'react-native'",
      "import React from 'react'",
      "import renderer from 'react-test-renderer'",
      "import { Provider } from 'react-redux'",
      "",
      "import store from '~/store'",
      "import ${1:${TM_FILENAME_BASE}} from '../${1:${TM_FILENAME_BASE}}'",
      "",
      "describe('<${1:${TM_FILENAME_BASE}} />', () => {",
      "  const defaultProps = {}",
      "  const wrapper = renderer.create(",
      "    <Provider store={store}>",
      "      <${1:${TM_FILENAME_BASE}} {...defaultProps} />",
      "    </Provider>,",
      "  )",
      "",
      "  test('render', () => {",
      "    expect(wrapper).toMatchSnapshot()",
      "  })",
      "})",
    ],
  },
  {
    key: "tests-setup-react-test",
    prefix: "stest",
    description: "Setup React Test · stest",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: [
      "import React from 'react'",
      "import renderer from 'react-test-renderer'",
      "",
      "import { ${1:${TM_FILENAME_BASE}} } from '../${1:${TM_FILENAME_BASE}}'",
      "",
      "describe('<${1:${TM_FILENAME_BASE}} />', () => {",
      "  const defaultProps = {}",
      "  const wrapper = renderer.create(<${1:${TM_FILENAME_BASE}} {...defaultProps} />)",
      "",
      "  test('render', () => {",
      "    expect(wrapper).toMatchSnapshot()",
      "  })",
      "})",
    ],
  },
  {
    key: "tests-test-async-block",
    prefix: "testa",
    description: "Testing `asynchronous test` block · testa",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "test('should ${1:first}', async () => { ${2:second} })",
  },
  {
    key: "tests-test-block",
    prefix: "test",
    description: "Testing `test` block · test",
    languages: [
      "typescript",
      "typescriptreact",
      "javascript",
      "javascriptreact",
    ],
    body: "test('should ${1:first}', () => { ${2:second} })",
  },
];
