/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "vitest-describe-suite",
    prefix: "vtdesc",
    description: "Vitest describe suite",
    languages: ["typescript", "javascript"],
    body: ['describe("${1:Feature}", () => {', "  $0", "});"],
  },
  {
    key: "vitest-it-test",
    prefix: "vtit",
    description: "Vitest it test case",
    languages: ["typescript", "javascript"],
    body: ['it("${1:should behave as expected}", () => {', "  $0", "});"],
  },
  {
    key: "vitest-it-async",
    prefix: "vtita",
    description: "Vitest async it test case",
    languages: ["typescript", "javascript"],
    body: ['it("${1:should behave as expected}", async () => {', "  $0", "});"],
  },
  {
    key: "vitest-before-each",
    prefix: "vtbe",
    description: "Vitest beforeEach setup hook",
    languages: ["typescript", "javascript"],
    body: ["beforeEach(() => {", "  $0", "});"],
  },
  {
    key: "vitest-after-each",
    prefix: "vtae",
    description: "Vitest afterEach cleanup hook",
    languages: ["typescript", "javascript"],
    body: ["afterEach(() => {", "  $0", "});"],
  },
  {
    key: "vitest-mock-fn",
    prefix: "vtmock",
    description: "Vitest vi.fn mock function",
    languages: ["typescript", "javascript"],
    body: "const ${1:mockFn} = vi.fn();",
  },
  {
    key: "vitest-mock-module",
    prefix: "vtmockmod",
    description: "Vitest vi.mock module mock",
    languages: ["typescript", "javascript"],
    body: [
      'vi.mock("${1:module}", () => ({',
      "  ${2:exportName}: vi.fn(),",
      "}));",
    ],
  },
  {
    key: "vitest-expect-throw",
    prefix: "vtthrow",
    description: "Vitest expect to throw assertion",
    languages: ["typescript", "javascript"],
    body: "await expect(${1:action}).rejects.toThrow(${2:Error});",
  },
  {
    key: "vitest-rtl-render",
    prefix: "vtrender",
    description: "Vitest RTL render component",
    languages: ["typescriptreact", "javascriptreact"],
    body: [
      'import { render, screen } from "@testing-library/react";',
      'import userEvent from "@testing-library/user-event";',
      "",
      "render(<${1:Component} ${2:props} />);",
      "$0",
    ],
    variants: {
      typescriptreact: {
        body: [
          'import { render, screen } from "@testing-library/react";',
          'import userEvent from "@testing-library/user-event";',
          'import { ${1:Component} } from "./${1:Component}";',
          "",
          "render(<${1:Component} ${2:defaultProps} />);",
          "$0",
        ],
      },
    },
  },
  {
    key: "vitest-rtl-user-click",
    prefix: "vtclick",
    description: "Vitest RTL userEvent click interaction",
    languages: ["typescriptreact", "javascriptreact"],
    body: [
      "const user = userEvent.setup();",
      'await user.click(screen.getByRole("${1:button}", { name: /${2:label}/i }));',
      "$0",
    ],
  },
  {
    key: "vitest-rtl-wait-for",
    prefix: "vtwait",
    description: "Vitest RTL waitFor async assertion",
    languages: ["typescriptreact", "javascriptreact"],
    body: [
      "await waitFor(() => {",
      "  expect(screen.getByText(/${1:expected}/i)).toBeInTheDocument();",
      "});",
    ],
  },
  {
    key: "vitest-rtl-component-test",
    prefix: "vtcmp",
    description: "Vitest RTL component test template",
    languages: ["typescriptreact", "javascriptreact"],
    body: [
      'import { render, screen } from "@testing-library/react";',
      'import userEvent from "@testing-library/user-event";',
      'import { ${1:Component} } from "./${1:Component}";',
      "",
      'describe("${1:Component}", () => {',
      '  it("${2:renders and responds to interaction}", async () => {',
      "    const user = userEvent.setup();",
      "    render(<${1:Component} />);",
      "",
      '    expect(screen.getByRole("${3:heading}", { name: /${4:Title}/i })).toBeInTheDocument();',
      '    await user.click(screen.getByRole("${5:button}", { name: /${6:Action}/i }));',
      "    $0",
      "  });",
      "});",
    ],
  },
  {
    key: "vitest-msw-handler-get",
    prefix: "vtmswget",
    description: "MSW http.get request handler",
    languages: ["typescript", "javascript"],
    body: [
      'http.get("${1:/api/resource}", () => {',
      "  return HttpResponse.json({",
      "    $0",
      "  });",
    ],
  },
  {
    key: "vitest-msw-handler-post",
    prefix: "vtmswpost",
    description: "MSW http.post request handler",
    languages: ["typescript", "javascript"],
    body: [
      'http.post("${1:/api/resource}", async ({ request }) => {',
      "  const body = await request.json();",
      "  return HttpResponse.json({",
      "    $0",
      "  }, { status: ${2:201} });",
    ],
  },
  {
    key: "vitest-msw-server-setup",
    prefix: "vtmsw",
    description: "MSW server setup for Vitest",
    languages: ["typescript", "javascript"],
    body: [
      'import { setupServer } from "msw/node";',
      'import { http, HttpResponse } from "msw";',
      "",
      "const handlers = [",
      '  http.get("${1:/api/health}", () => HttpResponse.json({ ok: true })),',
      "  $0",
      "];",
      "",
      "export const server = setupServer(...handlers);",
      "",
      'beforeAll(() => server.listen({ onUnhandledRequest: "error" }));',
      "afterEach(() => server.resetHandlers());",
      "afterAll(() => server.close());",
    ],
  },
  {
    key: "vitest-hook-component-test",
    prefix: "vthook",
    description: "Vitest React hook test with renderHook",
    languages: ["typescriptreact", "javascriptreact"],
    body: [
      'import { renderHook, act } from "@testing-library/react";',
      'import { ${1:useHook} } from "./${1:useHook}";',
      "",
      'describe("${1:useHook}", () => {',
      '  it("${2:returns expected value}", () => {',
      "    const { result } = renderHook(() => ${1:useHook}(${3:args}));",
      "",
      "    act(() => {",
      "      $0",
      "    });",
      "",
      "    expect(result.current).toBe(${4:expected});",
      "  });",
      "});",
    ],
  },
];
