/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "ts-interface",
    prefix: "interface",
    description: "TypeScript interface",
    languages: ["typescript"],
    body: [
      "interface ${1:Name} {",
      "  $0",
      "}",
    ],
  },
  {
    key: "ts-type-alias",
    prefix: "type",
    description: "TypeScript type alias",
    languages: ["typescript"],
    body: "type ${1:Name} = ${2:type};",
  },
  {
    key: "ts-enum",
    prefix: "enum",
    description: "TypeScript enum",
    languages: ["typescript"],
    body: [
      "enum ${1:Name} {",
      "  ${2:Value},",
      "  $0",
      "}",
    ],
  },
  {
    key: "ts-function-typed",
    prefix: "fn",
    description: "TypeScript function with types",
    languages: ["typescript"],
    body: [
      "function ${1:name}(${2:params}: ${3:ParamsType}): ${4:ReturnType} {",
      "  $0",
      "}",
    ],
  },
  {
    key: "ts-async-function-typed",
    prefix: "afn",
    description: "TypeScript async function with types",
    languages: ["typescript"],
    body: [
      "async function ${1:name}(${2:params}: ${3:ParamsType}): Promise<${4:ReturnType}> {",
      "  $0",
      "}",
    ],
  },
  {
    key: "ts-arrow-function-typed",
    prefix: "arrow",
    description: "TypeScript arrow function with types",
    languages: ["typescript"],
    body: [
      "const ${1:name} = (${2:params}: ${3:ParamsType}): ${4:ReturnType} => {",
      "  $0",
      "};",
    ],
  },
  {
    key: "ts-generic-function",
    prefix: "gfn",
    description: "TypeScript generic function",
    languages: ["typescript"],
    body: [
      "function ${1:name}<${2:T}>(${3:param}: ${2:T}): ${4:ReturnType} {",
      "  $0",
      "}",
    ],
  },
  {
    key: "ts-generic-type",
    prefix: "gtype",
    description: "TypeScript generic type alias",
    languages: ["typescript"],
    body: "type ${1:Name}<${2:T}> = ${3:type};",
  },
  {
    key: "ts-import-type",
    prefix: "imtype",
    description: "TypeScript import type",
    languages: ["typescript"],
    body: "import type { ${1:Type} } from \"${2:module}\";",
  },
  {
    key: "ts-export-type",
    prefix: "extype",
    description: "TypeScript export type",
    languages: ["typescript"],
    body: "export type { ${1:Type} };",
  },
  {
    key: "ts-satisfies",
    prefix: "satisfies",
    description: "TypeScript satisfies expression",
    languages: ["typescript"],
    body: "${1:value} satisfies ${2:Type}",
  },
  {
    key: "ts-as-const",
    prefix: "asconst",
    description: "TypeScript as const assertion",
    languages: ["typescript"],
    body: "${1:value} as const",
  },
  {
    key: "ts-partial-type",
    prefix: "partial",
    description: "TypeScript Partial utility type",
    languages: ["typescript"],
    body: "Partial<${1:Type}>",
  },
  {
    key: "ts-pick-type",
    prefix: "pick",
    description: "TypeScript Pick utility type",
    languages: ["typescript"],
    body: "Pick<${1:Type}, ${2:\"key\"}>",
  },
  {
    key: "ts-omit-type",
    prefix: "omit",
    description: "TypeScript Omit utility type",
    languages: ["typescript"],
    body: "Omit<${1:Type}, ${2:\"key\"}>",
  },
  {
    key: "ts-record-type",
    prefix: "record",
    description: "TypeScript Record utility type",
    languages: ["typescript"],
    body: "Record<${1:Key}, ${2:Value}>",
  },
  {
    key: "ts-readonly-type",
    prefix: "readonly",
    description: "TypeScript Readonly utility type",
    languages: ["typescript"],
    body: "Readonly<${1:Type}>",
  },
  {
    key: "ts-union-type",
    prefix: "union",
    description: "TypeScript union type",
    languages: ["typescript"],
    body: "${1:TypeA} | ${2:TypeB}",
  },
  {
    key: "ts-intersection-type",
    prefix: "intersect",
    description: "TypeScript intersection type",
    languages: ["typescript"],
    body: "${1:TypeA} & ${2:TypeB}",
  },
  {
    key: "ts-type-guard",
    prefix: "typeguard",
    description: "TypeScript type guard function",
    languages: ["typescript"],
    body: [
      "function is${1:Type}(value: unknown): value is ${1:Type} {",
      "  return $0;",
      "}",
    ],
  },
  {
    key: "ts-class-typed",
    prefix: "class",
    description: "TypeScript class with typed constructor",
    languages: ["typescript"],
    body: [
      "class ${1:Name} {",
      "  constructor(private readonly ${2:prop}: ${3:Type}) {",
      "    $0",
      "  }",
      "}",
    ],
  },
  {
    key: "ts-try-catch",
    prefix: "try",
    description: "TypeScript try catch",
    languages: ["typescript"],
    body: [
      "try {",
      "  $1",
      "} catch (error) {",
      "  $0",
      "}",
    ],
  },
  {
    key: "ts-import",
    prefix: "im",
    description: "TypeScript import statement",
    languages: ["typescript"],
    body: "import ${1:module} from \"${2:module}\";",
  },
  {
    key: "ts-const-assertion-object",
    prefix: "constobj",
    description: "TypeScript const object assertion",
    languages: ["typescript"],
    body: [
      "const ${1:name} = {",
      "  $0",
      "} as const;",
    ],
  },
  {
    key: "ts-discriminated-union",
    prefix: "discriminated",
    description: "TypeScript discriminated union",
    languages: ["typescript"],
    body: [
      "type ${1:Result} =",
      "  | { status: \"success\"; data: ${2:DataType} }",
      "  | { status: \"error\"; error: Error };",
    ],
  },
  {
    key: "ts-required-type",
    prefix: "required",
    description: "TypeScript Required utility type",
    languages: ["typescript"],
    body: "Required<${1:Type}>",
  },
  {
    key: "ts-nonnullable-type",
    prefix: "nonnullable",
    description: "TypeScript NonNullable utility type",
    languages: ["typescript"],
    body: "NonNullable<${1:Type}>",
  },
  {
    key: "ts-extract-type",
    prefix: "extract",
    description: "TypeScript Extract utility type",
    languages: ["typescript"],
    body: "Extract<${1:Union}, ${2:Member}>",
  },
  {
    key: "ts-exclude-type",
    prefix: "exclude",
    description: "TypeScript Exclude utility type",
    languages: ["typescript"],
    body: "Exclude<${1:Union}, ${2:Member}>",
  },
  {
    key: "ts-returntype",
    prefix: "returntype",
    description: "TypeScript ReturnType utility type",
    languages: ["typescript"],
    body: "ReturnType<typeof ${1:fn}>",
  },
  {
    key: "ts-parameterstype",
    prefix: "parameters",
    description: "TypeScript Parameters utility type",
    languages: ["typescript"],
    body: "Parameters<typeof ${1:fn}>",
  },
  {
    key: "ts-awaited-type",
    prefix: "awaited",
    description: "TypeScript Awaited utility type",
    languages: ["typescript"],
    body: "Awaited<${1:PromiseType}>",
  },
  {
    key: "ts-keyof-type",
    prefix: "keyof",
    description: "TypeScript keyof type",
    languages: ["typescript"],
    body: "keyof ${1:Type}",
  },
  {
    key: "ts-typeof",
    prefix: "typeof",
    description: "TypeScript typeof type query",
    languages: ["typescript"],
    body: "typeof ${1:value}",
  },
  {
    key: "ts-assert-never",
    prefix: "assertnever",
    description: "TypeScript assertNever exhaustiveness helper",
    languages: ["typescript"],
    body: [
      "function assertNever(value: never): never {",
      "  throw new Error(`Unexpected value: ${String(value)}`);",
      "}",
    ],
  },
  {
    key: "ts-fetch-typed",
    prefix: "fetch",
    description: "TypeScript typed fetch helper",
    languages: ["typescript"],
    body: [
      "async function fetch${1:Resource}(url: string, init?: RequestInit): Promise<${2:ResponseType}> {",
      "  const response = await fetch(url, {",
      "    ...init,",
      "    headers: {",
      "      Accept: \"application/json\",",
      "      ...init?.headers,",
      "    },",
      "  });",
      "",
      "  if (!response.ok) {",
      "    throw new Error(`Request failed: ${response.status}`);",
      "  }",
      "",
      "  return response.json() as Promise<${2:ResponseType}>;",
      "}",
    ],
  },
  {
    key: "ts-result-type",
    prefix: "result",
    description: "TypeScript Result type alias",
    languages: ["typescript"],
    body: "type Result<T, E = Error> = { ok: true; value: T } | { ok: false; error: E };",
  },
  {
    key: "ts-branded-type",
    prefix: "branded",
    description: "TypeScript branded type",
    languages: ["typescript"],
    body: [
      "type ${1:Brand} = ${2:string} & { readonly __brand: unique symbol };",
      "",
      "function create${1:Brand}(value: ${2:string}): ${1:Brand} {",
      "  return value as ${1:Brand};",
      "}",
    ],
  },
  {
    key: "ts-try-catch-narrow",
    prefix: "trynarrow",
    description: "TypeScript try catch with error narrowing",
    languages: ["typescript"],
    body: [
      "try {",
      "  $1",
      "} catch (error) {",
      "  if (error instanceof Error) {",
      "    $0",
      "  } else {",
      "    throw error;",
      "  }",
      "}",
    ],
  },
  {
    key: "ts-const-enum",
    prefix: "constenum",
    description: "TypeScript const enum",
    languages: ["typescript"],
    body: [
      "const enum ${1:Name} {",
      "  ${2:Value},",
      "  $0",
      "}",
    ],
  },
  {
    key: "ts-deep-partial",
    prefix: "deeppartial",
    description: "TypeScript DeepPartial recursive type",
    languages: ["typescript"],
    body: [
      "type DeepPartial<T> = {",
      "  [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K];",
      "};",
    ],
  },
  {
    key: "ts-template-literal-type",
    prefix: "tpltype",
    description: "TypeScript template literal type",
    languages: ["typescript"],
    body: "type ${1:EventName} = `${2:prefix}:${3:action}`;",
  },
  {
    key: "ts-const-generic",
    prefix: "constgen",
    description: "TypeScript const generic type parameter",
    languages: ["typescript"],
    body: [
      "function ${1:defineConfig}<const T extends readonly string[]>(config: T): T {",
      "  return config;",
      "}",
    ],
  },
  {
    key: "ts-infer-utility",
    prefix: "inferutil",
    description: "TypeScript infer inside conditional type",
    languages: ["typescript"],
    body: [
      "type ${1:Unwrap}<T> = T extends Promise<infer U> ? U : T;",
    ],
  },
  {
    key: "ts-module-augmentation",
    prefix: "augment",
    description: "TypeScript module augmentation",
    languages: ["typescript"],
    body: [
      "declare module \"${1:module}\" {",
      "  interface ${2:Type} {",
      "    ${3:field}: ${4:string};",
      "  }",
      "}",
    ],
  },
  {
    key: "ts-narrow-array",
    prefix: "narrowarr",
    description: "TypeScript narrow unknown array items",
    languages: ["typescript"],
    body: [
      "function is${1:Item}(value: unknown): value is ${1:Item} {",
      "  return typeof value === \"object\" && value !== null && \"${2:id}\" in value;",
      "}",
      "",
      "const ${3:items} = (raw as unknown[]).filter(is${1:Item});",
    ],
  },
  {
    key: "ts-zod-infer-export",
    prefix: "ztype",
    description: "TypeScript export type from Zod schema",
    languages: ["typescript"],
    body: [
      "export const ${1:Schema} = z.object({",
      "  ${2:field}: z.string(),",
      "  $0",
      "});",
      "",
      "export type ${3:Type} = z.infer<typeof ${1:Schema}>;",
    ],
  },
];
