/** @type {import('../validate.js').SnippetDefinition[]} */
export default [
  {
    key: "zod-object-schema",
    prefix: "zobject",
    description: "Zod object schema",
    languages: ["typescript", "javascript"],
    body: [
      "const ${1:Schema} = z.object({",
      "  ${2:field}: z.${3|string()|}(),",
      "  $0",
      "});",
    ],
  },
  {
    key: "zod-schema-infer",
    prefix: "zinfer",
    description: "Zod schema with inferred TypeScript type",
    languages: ["typescript"],
    body: [
      "const ${1:Schema} = z.object({",
      "  ${2:field}: z.${3|string()|}(),",
      "  $0",
      "});",
      "",
      "type ${4:Type} = z.infer<typeof ${1:Schema}>;",
    ],
  },
  {
    key: "zod-safe-parse",
    prefix: "zsafe",
    description: "Zod safeParse with error handling",
    languages: ["typescript", "javascript"],
    body: [
      "const result = ${1:Schema}.safeParse(${2:input});",
      "",
      "if (!result.success) {",
      "  console.error(result.error.flatten());",
      "  return { ok: false, errors: result.error.flatten().fieldErrors };",
      "}",
      "",
      "return { ok: true, data: result.data };",
    ],
    variants: {
      typescript: {
        body: [
          "const result = ${1:Schema}.safeParse(${2:input});",
          "",
          "if (!result.success) {",
          "  return { ok: false as const, errors: result.error.flatten().fieldErrors };",
          "}",
          "",
          "return { ok: true as const, data: result.data };",
        ],
      },
    },
  },
  {
    key: "zod-discriminated-union",
    prefix: "zdisc",
    description: "Zod discriminated union schema",
    languages: ["typescript", "javascript"],
    body: [
      'const ${1:Schema} = z.discriminatedUnion("type", [',
      '  z.object({ type: z.literal("${2:success}"), data: z.${3|string()|}() }),',
      '  z.object({ type: z.literal("${4:error}"), message: z.string() }),',
      "]);",
    ],
  },
  {
    key: "zod-array-schema",
    prefix: "zarray",
    description: "Zod array schema with constraints",
    languages: ["typescript", "javascript"],
    body: "z.array(z.${1|string()|}()).min(${2:1}).max(${3:100})",
  },
  {
    key: "zod-enum-schema",
    prefix: "zenum",
    description: "Zod native enum schema",
    languages: ["typescript", "javascript"],
    body: 'z.enum(["${1:option-a}", "${2:option-b}"])',
  },
  {
    key: "zod-union-schema",
    prefix: "zunion",
    description: "Zod union schema",
    languages: ["typescript", "javascript"],
    body: "z.union([z.${1|string()|}(), z.${2|number()|}()])",
  },
  {
    key: "zod-refine-schema",
    prefix: "zrefine",
    description: "Zod schema with refine validation",
    languages: ["typescript", "javascript"],
    body: [
      "${1:Schema}.refine(",
      "  (${2:value}) => ${3:condition},",
      '  { message: "${4:Validation failed}" },',
      ")",
    ],
  },
  {
    key: "zod-coerce-number",
    prefix: "zcoerce",
    description: "Zod coerce number from string input",
    languages: ["typescript", "javascript"],
    body: "z.coerce.number().int().positive()",
  },
  {
    key: "zod-pick-omit",
    prefix: "zpick",
    description: "Zod pick subset of object schema",
    languages: ["typescript", "javascript"],
    body: "${1:Schema}.pick({ ${2:field}: true })",
  },
  {
    key: "zod-form-action-parse",
    prefix: "zform",
    description: "Zod parse FormData in server action",
    languages: ["typescript"],
    body: [
      "const raw = Object.fromEntries(formData.entries());",
      "const parsed = ${1:Schema}.safeParse(raw);",
      "",
      "if (!parsed.success) {",
      "  return { ok: false as const, errors: parsed.error.flatten().fieldErrors };",
      "}",
      "",
      "$0",
      "return { ok: true as const, data: parsed.data };",
    ],
  },
  {
    key: "zod-error-format",
    prefix: "zerrors",
    description: "Zod format validation errors for API response",
    languages: ["typescript", "javascript"],
    body: [
      "function formatZodErrors(error: z.ZodError) {",
      "  return error.issues.map((issue) => ({",
      '    path: issue.path.join("."),',
      "    message: issue.message,",
      "  }));",
      "}",
    ],
    variants: {
      javascript: {
        body: [
          "function formatZodErrors(error) {",
          "  return error.issues.map((issue) => ({",
          '    path: issue.path.join("."),',
          "    message: issue.message,",
          "  }));",
          "}",
        ],
      },
    },
  },
];
